//! Export quantum circuits to hardware formats.
//!
//! Supported formats:
//! - OpenQASM 2.0 (universal)
//! - OpenQASM 3.0
//! - IBM Quantum JSON
//! - IonQ JSON
//! - Google Cirq Python
//! - AWS Braket Python

use crate::gates::{GateKind, GateOp};
use serde::{Serialize, Deserialize};
use std::fmt::Write;

/// Export format selector.
#[derive(Debug, Clone, Copy)]
pub enum ExportFormat {
    Qasm2,
    Qasm3,
    Ibm,
    IonQ,
    Cirq,
    Braket,
}

/// Circuit metadata for export.
#[derive(Debug, Clone)]
pub struct CircuitInfo {
    pub name: String,
    pub n_qubits: usize,
    pub n_clbits: usize,
    pub gates: Vec<GateOp>,
}

impl CircuitInfo {
    pub fn from_engine_log(name: &str, n_qubits: usize, gates: Vec<GateOp>) -> Self {
        CircuitInfo {
            name: name.to_string(),
            n_qubits,
            n_clbits: n_qubits,
            gates,
        }
    }
}

/// Export a circuit to a string in the specified format.
pub fn export_circuit(circuit: &CircuitInfo, format: ExportFormat) -> String {
    match format {
        ExportFormat::Qasm2 => export_qasm2(circuit),
        ExportFormat::Qasm3 => export_qasm3(circuit),
        ExportFormat::Ibm => export_ibm_json(circuit),
        ExportFormat::IonQ => export_ionq_json(circuit),
        ExportFormat::Cirq => export_cirq_python(circuit),
        ExportFormat::Braket => export_braket_python(circuit),
    }
}

fn export_qasm2(c: &CircuitInfo) -> String {
    let mut out = String::new();
    writeln!(out, "OPENQASM 2.0;").unwrap();
    writeln!(out, "include \"qelib1.inc\";").unwrap();
    writeln!(out, "// Generated by Sansqrit v0.1.0").unwrap();
    writeln!(out, "// Circuit: {}", c.name).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "qreg q[{}];", c.n_qubits).unwrap();
    writeln!(out, "creg c[{}];", c.n_clbits).unwrap();
    writeln!(out).unwrap();

    for gate in &c.gates {
        match gate.kind {
            GateKind::I => writeln!(out, "id q[{}];", gate.qubits[0]).unwrap(),
            GateKind::X => writeln!(out, "x q[{}];", gate.qubits[0]).unwrap(),
            GateKind::Y => writeln!(out, "y q[{}];", gate.qubits[0]).unwrap(),
            GateKind::Z => writeln!(out, "z q[{}];", gate.qubits[0]).unwrap(),
            GateKind::H => writeln!(out, "h q[{}];", gate.qubits[0]).unwrap(),
            GateKind::S => writeln!(out, "s q[{}];", gate.qubits[0]).unwrap(),
            GateKind::Sdg => writeln!(out, "sdg q[{}];", gate.qubits[0]).unwrap(),
            GateKind::T => writeln!(out, "t q[{}];", gate.qubits[0]).unwrap(),
            GateKind::Tdg => writeln!(out, "tdg q[{}];", gate.qubits[0]).unwrap(),
            GateKind::SX => writeln!(out, "sx q[{}];", gate.qubits[0]).unwrap(),
            GateKind::Rx => writeln!(out, "rx({}) q[{}];", gate.params[0], gate.qubits[0]).unwrap(),
            GateKind::Ry => writeln!(out, "ry({}) q[{}];", gate.params[0], gate.qubits[0]).unwrap(),
            GateKind::Rz => writeln!(out, "rz({}) q[{}];", gate.params[0], gate.qubits[0]).unwrap(),
            GateKind::Phase => writeln!(out, "p({}) q[{}];", gate.params[0], gate.qubits[0]).unwrap(),
            GateKind::U3 => writeln!(out, "u3({},{},{}) q[{}];",
                gate.params[0], gate.params[1], gate.params[2], gate.qubits[0]).unwrap(),
            GateKind::CNOT => writeln!(out, "cx q[{}],q[{}];", gate.qubits[0], gate.qubits[1]).unwrap(),
            GateKind::CZ => writeln!(out, "cz q[{}],q[{}];", gate.qubits[0], gate.qubits[1]).unwrap(),
            GateKind::CY => writeln!(out, "cy q[{}],q[{}];", gate.qubits[0], gate.qubits[1]).unwrap(),
            GateKind::SWAP => writeln!(out, "swap q[{}],q[{}];", gate.qubits[0], gate.qubits[1]).unwrap(),
            GateKind::CRz => writeln!(out, "crz({}) q[{}],q[{}];",
                gate.params[0], gate.qubits[0], gate.qubits[1]).unwrap(),
            GateKind::CP => writeln!(out, "cp({}) q[{}],q[{}];",
                gate.params[0], gate.qubits[0], gate.qubits[1]).unwrap(),
            GateKind::RZZ => writeln!(out, "rzz({}) q[{}],q[{}];",
                gate.params[0], gate.qubits[0], gate.qubits[1]).unwrap(),
            GateKind::Toffoli => writeln!(out, "ccx q[{}],q[{}],q[{}];",
                gate.qubits[0], gate.qubits[1], gate.qubits[2]).unwrap(),
            GateKind::Fredkin => writeln!(out, "cswap q[{}],q[{}],q[{}];",
                gate.qubits[0], gate.qubits[1], gate.qubits[2]).unwrap(),
            _ => writeln!(out, "// unsupported gate: {:?}", gate.kind).unwrap(),
        }
    }

    // Add measurements
    writeln!(out).unwrap();
    for i in 0..c.n_qubits {
        writeln!(out, "measure q[{}] -> c[{}];", i, i).unwrap();
    }

    out
}

fn export_qasm3(c: &CircuitInfo) -> String {
    let mut out = String::new();
    writeln!(out, "OPENQASM 3.0;").unwrap();
    writeln!(out, "include \"stdgates.inc\";").unwrap();
    writeln!(out, "// Generated by Sansqrit v0.1.0").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "qubit[{}] q;", c.n_qubits).unwrap();
    writeln!(out, "bit[{}] c;", c.n_clbits).unwrap();
    writeln!(out).unwrap();

    for gate in &c.gates {
        let qasm = gate_to_qasm3(gate);
        writeln!(out, "{}", qasm).unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "c = measure q;").unwrap();
    out
}

fn gate_to_qasm3(gate: &GateOp) -> String {
    match gate.kind {
        GateKind::H => format!("h q[{}];", gate.qubits[0]),
        GateKind::X => format!("x q[{}];", gate.qubits[0]),
        GateKind::Y => format!("y q[{}];", gate.qubits[0]),
        GateKind::Z => format!("z q[{}];", gate.qubits[0]),
        GateKind::CNOT => format!("cx q[{}], q[{}];", gate.qubits[0], gate.qubits[1]),
        GateKind::Rx => format!("rx({}) q[{}];", gate.params[0], gate.qubits[0]),
        GateKind::Ry => format!("ry({}) q[{}];", gate.params[0], gate.qubits[0]),
        GateKind::Rz => format!("rz({}) q[{}];", gate.params[0], gate.qubits[0]),
        _ => format!("// {:?} q{:?};", gate.kind, gate.qubits),
    }
}

fn export_ibm_json(c: &CircuitInfo) -> String {
    #[derive(Serialize)]
    struct IbmCircuit {
        header: IbmHeader,
        instructions: Vec<IbmInstruction>,
    }

    #[derive(Serialize)]
    struct IbmHeader {
        name: String,
        n_qubits: usize,
        memory_slots: usize,
    }

    #[derive(Serialize)]
    struct IbmInstruction {
        name: String,
        qubits: Vec<usize>,
        #[serde(skip_serializing_if = "Vec::is_empty")]
        params: Vec<f64>,
    }

    let instructions: Vec<IbmInstruction> = c.gates.iter().map(|g| {
        IbmInstruction {
            name: g.kind.name().to_lowercase(),
            qubits: g.qubits.clone(),
            params: g.params.clone(),
        }
    }).collect();

    let circuit = IbmCircuit {
        header: IbmHeader {
            name: c.name.clone(),
            n_qubits: c.n_qubits,
            memory_slots: c.n_clbits,
        },
        instructions,
    };

    serde_json::to_string_pretty(&circuit).unwrap_or_default()
}

fn export_ionq_json(c: &CircuitInfo) -> String {
    #[derive(Serialize)]
    struct IonQCircuit {
        qubits: usize,
        circuit: Vec<IonQGate>,
    }

    #[derive(Serialize)]
    struct IonQGate {
        gate: String,
        targets: Vec<usize>,
        #[serde(skip_serializing_if = "Option::is_none")]
        controls: Option<Vec<usize>>,
        #[serde(skip_serializing_if = "Option::is_none")]
        rotation: Option<f64>,
    }

    let gates: Vec<IonQGate> = c.gates.iter().map(|g| {
        match g.kind {
            GateKind::CNOT => IonQGate {
                gate: "cnot".into(),
                targets: vec![g.qubits[1]],
                controls: Some(vec![g.qubits[0]]),
                rotation: None,
            },
            GateKind::Rx => IonQGate {
                gate: "rx".into(),
                targets: vec![g.qubits[0]],
                controls: None,
                rotation: Some(g.params[0]),
            },
            _ => IonQGate {
                gate: g.kind.name().to_lowercase(),
                targets: g.qubits.clone(),
                controls: None,
                rotation: g.params.first().copied(),
            },
        }
    }).collect();

    let circuit = IonQCircuit { qubits: c.n_qubits, circuit: gates };
    serde_json::to_string_pretty(&circuit).unwrap_or_default()
}

fn export_cirq_python(c: &CircuitInfo) -> String {
    let mut out = String::new();
    writeln!(out, "# Generated by Sansqrit v0.1.0").unwrap();
    writeln!(out, "import cirq").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "qubits = cirq.LineQubit.range({})", c.n_qubits).unwrap();
    writeln!(out, "circuit = cirq.Circuit()").unwrap();
    writeln!(out).unwrap();

    for gate in &c.gates {
        let line = match gate.kind {
            GateKind::H => format!("circuit.append(cirq.H(qubits[{}]))", gate.qubits[0]),
            GateKind::X => format!("circuit.append(cirq.X(qubits[{}]))", gate.qubits[0]),
            GateKind::Y => format!("circuit.append(cirq.Y(qubits[{}]))", gate.qubits[0]),
            GateKind::Z => format!("circuit.append(cirq.Z(qubits[{}]))", gate.qubits[0]),
            GateKind::CNOT => format!("circuit.append(cirq.CNOT(qubits[{}], qubits[{}]))", gate.qubits[0], gate.qubits[1]),
            GateKind::CZ => format!("circuit.append(cirq.CZ(qubits[{}], qubits[{}]))", gate.qubits[0], gate.qubits[1]),
            GateKind::SWAP => format!("circuit.append(cirq.SWAP(qubits[{}], qubits[{}]))", gate.qubits[0], gate.qubits[1]),
            GateKind::Rx => format!("circuit.append(cirq.rx({}).on(qubits[{}]))", gate.params[0], gate.qubits[0]),
            GateKind::Ry => format!("circuit.append(cirq.ry({}).on(qubits[{}]))", gate.params[0], gate.qubits[0]),
            GateKind::Rz => format!("circuit.append(cirq.rz({}).on(qubits[{}]))", gate.params[0], gate.qubits[0]),
            GateKind::Toffoli => format!("circuit.append(cirq.TOFFOLI(qubits[{}], qubits[{}], qubits[{}]))",
                gate.qubits[0], gate.qubits[1], gate.qubits[2]),
            _ => format!("# Unsupported gate: {:?}", gate.kind),
        };
        writeln!(out, "{}", line).unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "circuit.append(cirq.measure(*qubits, key='result'))").unwrap();
    writeln!(out, "print(circuit)").unwrap();
    out
}

fn export_braket_python(c: &CircuitInfo) -> String {
    let mut out = String::new();
    writeln!(out, "# Generated by Sansqrit v0.1.0").unwrap();
    writeln!(out, "from braket.circuits import Circuit").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "circuit = Circuit()").unwrap();
    writeln!(out).unwrap();

    for gate in &c.gates {
        let line = match gate.kind {
            GateKind::H => format!("circuit.h({})", gate.qubits[0]),
            GateKind::X => format!("circuit.x({})", gate.qubits[0]),
            GateKind::Y => format!("circuit.y({})", gate.qubits[0]),
            GateKind::Z => format!("circuit.z({})", gate.qubits[0]),
            GateKind::CNOT => format!("circuit.cnot({}, {})", gate.qubits[0], gate.qubits[1]),
            GateKind::CZ => format!("circuit.cz({}, {})", gate.qubits[0], gate.qubits[1]),
            GateKind::SWAP => format!("circuit.swap({}, {})", gate.qubits[0], gate.qubits[1]),
            GateKind::Rx => format!("circuit.rx({}, {})", gate.qubits[0], gate.params[0]),
            GateKind::Ry => format!("circuit.ry({}, {})", gate.qubits[0], gate.params[0]),
            GateKind::Rz => format!("circuit.rz({}, {})", gate.qubits[0], gate.params[0]),
            GateKind::Toffoli => format!("circuit.ccnot({}, {}, {})",
                gate.qubits[0], gate.qubits[1], gate.qubits[2]),
            _ => format!("# Unsupported: {:?}", gate.kind),
        };
        writeln!(out, "{}", line).unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "print(circuit)").unwrap();
    out
}

/// Write export to a file.
pub fn export_to_file(circuit: &CircuitInfo, format: ExportFormat, path: &str) -> std::io::Result<()> {
    let content = export_circuit(circuit, format);
    std::fs::write(path, content)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_circuit() -> CircuitInfo {
        CircuitInfo {
            name: "test_bell".into(),
            n_qubits: 2,
            n_clbits: 2,
            gates: vec![
                GateOp::single(GateKind::H, 0),
                GateOp::two(GateKind::CNOT, 0, 1),
            ],
        }
    }

    #[test]
    fn test_qasm2_export() {
        let qasm = export_qasm2(&sample_circuit());
        assert!(qasm.contains("OPENQASM 2.0"));
        assert!(qasm.contains("h q[0]"));
        assert!(qasm.contains("cx q[0],q[1]"));
    }

    #[test]
    fn test_ibm_json_export() {
        let json = export_ibm_json(&sample_circuit());
        assert!(json.contains("\"n_qubits\": 2"));
    }

    #[test]
    fn test_ionq_json_export() {
        let json = export_ionq_json(&sample_circuit());
        assert!(json.contains("\"qubits\": 2"));
    }

    #[test]
    fn test_cirq_export() {
        let py = export_cirq_python(&sample_circuit());
        assert!(py.contains("import cirq"));
        assert!(py.contains("cirq.H"));
    }

    #[test]
    fn test_braket_export() {
        let py = export_braket_python(&sample_circuit());
        assert!(py.contains("from braket"));
        assert!(py.contains("circuit.h(0)"));
    }
}
