//! QEC integration helpers for Stim and PyMatching workflows.

use crate::external::{detect_integration, IntegrationKind, IntegrationStatus};
use crate::gates::{GateKind, GateOp};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct QecIntegrationStatus {
    pub stim: IntegrationStatus,
    pub pymatching: IntegrationStatus,
    pub production_ready: bool,
    pub notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StimExport {
    pub circuit: String,
    pub unsupported_gates: Vec<String>,
    pub warnings: Vec<String>,
}

pub fn qec_integration_status() -> QecIntegrationStatus {
    let stim = detect_integration(IntegrationKind::Stim);
    let pymatching = detect_integration(IntegrationKind::PyMatching);
    let mut notes = Vec::new();
    if !stim.available {
        notes.push(
            "Install the Python 'stim' package for production stabilizer/QEC sampling.".to_string(),
        );
    }
    if !pymatching.available {
        notes.push("Install the Python 'pymatching' package for MWPM decoding.".to_string());
    }

    QecIntegrationStatus {
        production_ready: stim.available && pymatching.available,
        stim,
        pymatching,
        notes,
    }
}

pub fn export_stim_circuit(n_qubits: usize, gates: &[GateOp]) -> StimExport {
    let mut circuit = String::new();
    let mut unsupported = Vec::new();
    let mut warnings = Vec::new();

    circuit.push_str("# Generated by Sansqrit\n");
    circuit.push_str(&format!("QUBIT_COORDS(0, 0) 0\n# qubits: {}\n", n_qubits));

    for gate in gates {
        match gate.kind {
            GateKind::I => {}
            GateKind::H => push_single(&mut circuit, "H", gate),
            GateKind::X => push_single(&mut circuit, "X", gate),
            GateKind::Y => push_single(&mut circuit, "Y", gate),
            GateKind::Z => push_single(&mut circuit, "Z", gate),
            GateKind::S => push_single(&mut circuit, "S", gate),
            GateKind::Sdg => push_single(&mut circuit, "S_DAG", gate),
            GateKind::CNOT => push_multi(&mut circuit, "CX", gate),
            GateKind::CZ => push_multi(&mut circuit, "CZ", gate),
            GateKind::SWAP => push_multi(&mut circuit, "SWAP", gate),
            GateKind::T | GateKind::Tdg | GateKind::Toffoli | GateKind::Fredkin | GateKind::CCZ => {
                unsupported.push(format!("{:?}", gate.kind));
                warnings.push(format!(
                    "{:?} is non-Clifford or not supported by this Stim exporter path.",
                    gate.kind
                ));
            }
            _ => {
                unsupported.push(format!("{:?}", gate.kind));
                warnings.push(format!("No Stim mapping for {:?}", gate.kind));
            }
        }
    }

    StimExport {
        circuit,
        unsupported_gates: unsupported,
        warnings,
    }
}

fn push_single(out: &mut String, name: &str, gate: &GateOp) {
    if let Some(q) = gate.qubits.first() {
        out.push_str(&format!("{} {}\n", name, q));
    }
}

fn push_multi(out: &mut String, name: &str, gate: &GateOp) {
    let qubits: Vec<String> = gate.qubits.iter().map(|q| q.to_string()).collect();
    out.push_str(&format!("{} {}\n", name, qubits.join(" ")));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stim_export_clifford_circuit() {
        let export = export_stim_circuit(
            2,
            &[
                GateOp::single(GateKind::H, 0),
                GateOp::two(GateKind::CNOT, 0, 1),
            ],
        );
        assert!(export.circuit.contains("H 0"));
        assert!(export.circuit.contains("CX 0 1"));
        assert!(export.unsupported_gates.is_empty());
    }

    #[test]
    fn test_stim_export_flags_non_clifford() {
        let export = export_stim_circuit(1, &[GateOp::single(GateKind::T, 0)]);
        assert_eq!(export.unsupported_gates, vec!["T"]);
    }
}
