/**
 * src/blocks/registry_extra.js  — EXTRA BLOCKS PART A
 * ─────────────────────────────────────────────────────
 * Additional 280 blocks merged into the main registry.
 * Import this file from registry.js — do NOT use standalone.
 *
 * NEW CATEGORIES (Part A):
 *   quantum_ec   — Quantum Error Correction (15 blocks)
 *   optimization — Classical & Quantum Optimisation (18 blocks)
 *   nlp          — Natural Language Processing (16 blocks)
 *   cv           — Computer Vision (15 blocks)
 *   finance      — Quantum Finance (14 blocks)
 *   climate      — Climate & Environment (12 blocks)
 *   robotics     — Robotics & Control (12 blocks)
 *
 * EXPANDED EXISTING (Part A):
 *   quantum_gate — +20 gates
 *   quantum_algo — +18 algorithms
 *   quantum_meas — +8 measurements
 *   noise        — +6 noise models
 */

// ── Param helpers (mirrors registry.js) ──────────────────────────────────
const ps   = (key,label,val='',desc='')                  => ({key,label,type:'string', value:val,default:val,description:desc});
const pn   = (key,label,val=0,min=null,max=null,desc='') => ({key,label,type:'number', value:val,default:val,min,max,description:desc});
const pa   = (key,label,val=0,desc='')                   => ({key,label,type:'angle',  value:val,default:val,min:0,max:Math.PI*2,description:desc});
const pb   = (key,label,val=false,desc='')               => ({key,label,type:'bool',   value:val,default:val,description:desc});
const psel = (key,label,opts,val,desc='')                => ({key,label,type:'select', options:opts,value:val||opts[0],default:val||opts[0],description:desc});
const pc   = (key,label,val='',desc='')                  => ({key,label,type:'code',   value:val,default:val,description:desc});
const pn_  = (key,label,val=0,desc='')                   => ({key,label,type:'number', value:val,default:val,description:desc});
const pj   = (key,label,val='{}',desc='')                => ({key,label,type:'json',   value:val,default:val,description:desc});

const qIn  = (id='qi',l='Qubit in')     => ({id,dir:'in', dt:'qubit',    label:l});
const qOut = (id='qo',l='Qubit out')    => ({id,dir:'out',dt:'qubit',    label:l});
const rIn  = (id='ri',l='Register in')  => ({id,dir:'in', dt:'register', label:l});
const rOut = (id='ro',l='Register out') => ({id,dir:'out',dt:'register', label:l});
const cIn  = (id='ci',l='In')           => ({id,dir:'in', dt:'classical',label:l});
const cOut = (id='co',l='Out')          => ({id,dir:'out',dt:'classical',label:l});
const aIn  = (id='ai',l='In')           => ({id,dir:'in', dt:'any',      label:l});
const aOut = (id='ao',l='Out')          => ({id,dir:'out',dt:'any',      label:l});

const pq   = (key,label,val=0,desc='')                   => ({key,label,type:'qubit',  value:val,default:val,description:desc});
const BYPASS = [
  pb('bypass','Bypass this block',false),
  pb('code_override','Code override',false),
  pc('override_code','Custom .sq code',''),
];

// ── New category definitions ──────────────────────────────────────────────
export const EXTRA_CATEGORIES = {
  quantum_ec:   { label:'Quantum Error Correction', color:'#0F766E', icon:'🛡' },
  optimization: { label:'Optimisation',             color:'#B45309', icon:'⬆' },
  nlp:          { label:'NLP & Text AI',            color:'#6D28D9', icon:'📝' },
  cv:           { label:'Computer Vision',          color:'#0369A1', icon:'👁' },
  finance:      { label:'Quantum Finance',          color:'#065F46', icon:'📈' },
  climate:      { label:'Climate & Environment',    color:'#166534', icon:'🌍' },
  robotics:     { label:'Robotics & Control',       color:'#7C2D12', icon:'🤖' },
};

// ═══════════════════════════════════════════════════════════════════════════
// EXTRA BLOCKS
// ═══════════════════════════════════════════════════════════════════════════
export const EXTRA_BLOCKS = [

  // ───────────────────────────────────────────────────────────────────────
  // QUANTUM ERROR CORRECTION (15 blocks)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'steane_code', label:'Steane [[7,1,3]]', cat:'quantum_ec',
    color:'#0F766E', icon:'[[7]]',
    info:'7-qubit Steane code: encodes 1 logical qubit, corrects any single-qubit error. CSS construction from classical Hamming codes.',
    params:[ps('data_qubit','Logical qubit var','q_data'), pb('auto_correct','Auto-correct errors',true), ps('output_var','Output syndrome','steane_syn'), ...BYPASS],
    inputs:[qIn()], outputs:[rOut('logical','Logical qubit'), cOut('syndrome')],
    toSq: p=>`let ${p.output_var} = steane_encode(${p.data_qubit})`,
  },
  {
    id:'shor_code', label:'Shor [[9,1,3]]', cat:'quantum_ec',
    color:'#0F766E', icon:'[[9]]',
    info:'9-qubit Shor code: first quantum error correcting code. Concatenates phase-flip and bit-flip codes.',
    params:[ps('data_qubit','Logical qubit var','q_data'), pb('measure_stabilizers','Measure stabilizers',true), ps('output_var','Output','shor_result'), ...BYPASS],
    inputs:[qIn()], outputs:[rOut('logical')],
    toSq: p=>`let ${p.output_var} = shor_encode(${p.data_qubit})`,
  },
  {
    id:'surface_code', label:'Surface Code', cat:'quantum_ec',
    color:'#0F766E', icon:'SC',
    info:'Topological surface code: leading candidate for fault-tolerant QC. Threshold ~1%. Distance d requires d² physical qubits per logical qubit.',
    params:[pn('distance','Code distance d',3,3,15), psel('boundary','Boundary type',['planar','toric','rotated'],'rotated'), pn('rounds','Error detection rounds',3,1,100), pb('decoder','Use MWPM decoder',true), ps('output_var','Logical qubit var','surface_q'), ...BYPASS],
    inputs:[], outputs:[rOut('logical'), cOut('syndrome')],
    toSq: p=>`let ${p.output_var} = surface_code(d=${p.distance}, rounds=${p.rounds})`,
  },
  {
    id:'color_code', label:'Color Code', cat:'quantum_ec',
    color:'#0F766E', icon:'CC',
    info:'2D color code: supports transversal Clifford + T gates. Triangular lattice geometry.',
    params:[pn('distance','Distance d',3,3,11), psel('geometry','Lattice',['triangular','hexagonal'],'triangular'), ps('output_var','Logical var','color_q'), ...BYPASS],
    inputs:[], outputs:[rOut('logical')],
    toSq: p=>`let ${p.output_var} = color_code(d=${p.distance})`,
  },
  {
    id:'bit_flip_code', label:'Bit-Flip Code [[3,1,1]]', cat:'quantum_ec',
    color:'#0F766E', icon:'[[3]]',
    info:'Simplest repetition code: protects against single bit-flip errors only.',
    params:[ps('data_qubit','Data qubit','q_data'), ps('output_var','Output','bfc_result'), ...BYPASS],
    inputs:[qIn()], outputs:[rOut('logical')],
    toSq: p=>`let ${p.output_var} = bit_flip_encode(${p.data_qubit})`,
  },
  {
    id:'syndrome_measure', label:'Syndrome Measurement', cat:'quantum_ec',
    color:'#0F766E', icon:'SYN',
    info:'Measure error syndrome without disturbing logical qubit. Uses ancilla qubits.',
    params:[ps('code_var','Encoded register','logical_q'), psel('code_type','Code type',['steane','shor','surface','color'],'surface'), ps('output_syndrome','Syndrome variable','syndrome'), ...BYPASS],
    inputs:[rIn()], outputs:[rOut(), cOut('syndrome')],
    toSq: p=>`let ${p.output_syndrome} = measure_syndrome(${p.code_var})`,
  },
  {
    id:'error_correct', label:'Error Correction', cat:'quantum_ec',
    color:'#0F766E', icon:'FIX',
    info:'Apply correction operations based on measured syndrome.',
    params:[ps('code_var','Encoded register','logical_q'), ps('syndrome_var','Syndrome variable','syndrome'), psel('decoder','Decoder',['MWPM','UF','NN','lookup'],'MWPM'), ...BYPASS],
    inputs:[rIn(), cIn('syn','Syndrome')], outputs:[rOut()],
    toSq: p=>`error_correct(${p.code_var}, ${p.syndrome_var}, decoder="${p.decoder}")`,
  },
  {
    id:'logical_gate', label:'Logical Gate', cat:'quantum_ec',
    color:'#0F766E', icon:'L-G',
    info:'Apply gate to logical qubit (fault-tolerant). Clifford gates are transversal; T needs magic state distillation.',
    params:[ps('code_var','Logical register','logical_q'), psel('gate','Logical gate',['H','X','Y','Z','S','T','CNOT','CZ'],'H'), pn('target_logical','Target logical qubit',0,0,100), ...BYPASS],
    inputs:[rIn()], outputs:[rOut()],
    toSq: p=>`logical_${p.gate}(${p.code_var}, ${p.target_logical})`,
  },
  {
    id:'magic_state_distill', label:'Magic State Distillation', cat:'quantum_ec',
    color:'#0F766E', icon:'MSD',
    info:'Distil high-fidelity |T⟩ magic states needed for fault-tolerant T gates.',
    params:[pn('n_noisy','Noisy input states',15,7,100), pn('target_fidelity','Target fidelity',0.9999,0.99,1), ps('output_var','Output magic state','T_state'), ...BYPASS],
    inputs:[], outputs:[aOut('T_state')],
    toSq: p=>`let ${p.output_var} = magic_state_distill(n=${p.n_noisy})`,
  },
  {
    id:'fault_tolerant_prep', label:'FT State Prep', cat:'quantum_ec',
    color:'#0F766E', icon:'FT|ψ⟩',
    info:'Fault-tolerant preparation of |0⟩, |+⟩, or |T⟩ logical states.',
    params:[psel('state','Logical state',['|0⟩','|1⟩','|+⟩','|-⟩','|T⟩'],'|0⟩'), ps('code_var','Code var','logical_q'), ...BYPASS],
    inputs:[], outputs:[rOut('logical')],
    toSq: p=>`let ${p.code_var} = ft_prep("${p.state}")`,
  },
  {
    id:'qec_threshold', label:'QEC Threshold Sim', cat:'quantum_ec',
    color:'#0F766E', icon:'THR',
    info:'Simulate logical error rate vs physical error rate. Find code threshold.',
    params:[psel('code','Code',['surface','steane','color'],'surface'), pn('d_min','Min distance',3,3,7), pn('d_max','Max distance',9,5,21), pj('physical_errors','Physical error rates','[0.001,0.005,0.01,0.02]'), ps('output_var','Output','threshold_data'), ...BYPASS],
    inputs:[], outputs:[cOut('threshold_plot')],
    toSq: p=>`let ${p.output_var} = qec_threshold_sim("${p.code}")`,
  },
  {
    id:'decoder_mwpm', label:'MWPM Decoder', cat:'quantum_ec',
    color:'#0F766E', icon:'MWPM',
    info:'Minimum Weight Perfect Matching decoder for surface codes. O(n³) but highly optimised.',
    params:[ps('syndrome_var','Syndrome','syndrome'), pn('code_distance','Distance d',3,3,21), pb('weighted','Weighted edges',true), ps('output_var','Corrections','corrections'), ...BYPASS],
    inputs:[cIn('syn')], outputs:[cOut('corrections')],
    toSq: p=>`let ${p.output_var} = mwpm_decode(${p.syndrome_var}, d=${p.code_distance})`,
  },
  {
    id:'stabilizer_sim', label:'Stabilizer Simulator', cat:'quantum_ec',
    color:'#0F766E', icon:'STAB',
    info:'Clifford-only simulation via stabilizer tableaux. Efficient O(n²) for error analysis.',
    params:[pn('n_qubits','Physical qubits',50,2,10000), ps('circuit_var','Circuit','q'), pb('track_errors','Track error propagation',true), ps('output_var','Output','stab_result'), ...BYPASS],
    inputs:[rIn()], outputs:[cOut('result')],
    toSq: p=>`let ${p.output_var} = stabilizer_sim(${p.circuit_var}, n=${p.n_qubits})`,
  },
  {
    id:'resource_estimate', label:'Resource Estimator', cat:'quantum_ec',
    color:'#0F766E', icon:'RES',
    info:'Estimate physical qubit count, T-gate count, and runtime for fault-tolerant algorithm.',
    params:[ps('algorithm','Algorithm name','shor_2048'), pn('logical_error_rate','Target logical error rate',1e-12,1e-20,0.01), pn('physical_error_rate','Physical error rate',0.001,1e-6,0.1), ps('output_var','Output estimate','resource_est'), ...BYPASS],
    inputs:[], outputs:[cOut('estimate')],
    toSq: p=>`let ${p.output_var} = resource_estimate("${p.algorithm}", p_phys=${p.physical_error_rate})`,
  },
  {
    id:'concatenated_code', label:'Concatenated Code', cat:'quantum_ec',
    color:'#0F766E', icon:'CAT',
    info:'Concatenate inner and outer codes for multiplicative threshold improvement.',
    params:[psel('inner_code','Inner code',['bit_flip','phase_flip','steane'],'steane'), psel('outer_code','Outer code',['steane','shor','surface'],'steane'), pn('levels','Concatenation levels',2,1,5), ps('output_var','Logical var','concat_q'), ...BYPASS],
    inputs:[], outputs:[rOut('logical')],
    toSq: p=>`let ${p.output_var} = concatenated_code(inner="${p.inner_code}", outer="${p.outer_code}", levels=${p.levels})`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // OPTIMISATION (18 blocks)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'cobyla_opt', label:'COBYLA', cat:'optimization',
    color:'#B45309', icon:'OPT',
    info:'Constrained Optimisation By Linear Approximations. Derivative-free, robust for noisy VQE landscapes.',
    params:[ps('objective_fn','Objective function','cost_fn'), pj('initial_params','Initial params','[0.1, 0.2]'), pn('max_iter','Max iterations',1000,1,100000), pn('rhobeg','Initial step size',0.5,0.001,10), ps('output_var','Output','cobyla_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('params'), cOut('value')],
    toSq: p=>`let ${p.output_var} = cobyla(${p.objective_fn}, max_iter=${p.max_iter})`,
  },
  {
    id:'spsa_opt', label:'SPSA', cat:'optimization',
    color:'#B45309', icon:'SPSA',
    info:'Simultaneous Perturbation Stochastic Approximation. Scales to high-dimension VQE with only 2 cost evaluations per step.',
    params:[ps('objective_fn','Objective function','cost_fn'), pj('initial_params','Initial params','[0.1, 0.2]'), pn('max_iter','Max iterations',300,1,10000), pn('a','Step size a',0.1,0.001,10), pn('c','Perturbation c',0.1,0.001,1), ps('output_var','Output','spsa_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('params'), cOut('value')],
    toSq: p=>`let ${p.output_var} = spsa(${p.objective_fn}, max_iter=${p.max_iter})`,
  },
  {
    id:'adam_opt', label:'Adam Optimizer', cat:'optimization',
    color:'#B45309', icon:'Adam',
    info:'Adaptive Moment Estimation: Adam for quantum circuit parameter training.',
    params:[ps('objective_fn','Objective function','cost_fn'), pj('initial_params','Initial params','[0.1, 0.2]'), pn('lr','Learning rate',0.01,1e-5,1), pn('beta1','β₁',0.9,0,1), pn('beta2','β₂',0.999,0,1), pn('max_iter','Iterations',500,1,50000), ps('output_var','Output','adam_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('params'), cOut('loss_curve')],
    toSq: p=>`let ${p.output_var} = adam(${p.objective_fn}, lr=${p.lr})`,
  },
  {
    id:'genetic_algo', label:'Genetic Algorithm', cat:'optimization',
    color:'#B45309', icon:'GA',
    info:'Evolutionary optimisation: selection, crossover, mutation. For combinatorial and discrete problems.',
    params:[ps('fitness_fn','Fitness function','fitness_fn'), pn('population','Population size',100,10,10000), pn('generations','Generations',200,10,10000), pn('mutation_rate','Mutation rate',0.01,0,1), pn('crossover_rate','Crossover rate',0.8,0,1), ps('output_var','Best solution','ga_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('solution'), cOut('fitness_history')],
    toSq: p=>`let ${p.output_var} = genetic_algorithm(${p.fitness_fn}, pop=${p.population}, gen=${p.generations})`,
  },
  {
    id:'simulated_annealing', label:'Simulated Annealing', cat:'optimization',
    color:'#B45309', icon:'SA',
    info:'Probabilistic metaheuristic: accepts worse solutions with cooling probability. Avoids local minima.',
    params:[ps('objective_fn','Objective function','cost_fn'), pn('T_start','Start temperature',100,0.1,1e6), pn('T_end','End temperature',0.01,1e-6,1), pn('n_steps','Steps',10000,100,1e9), psel('cooling','Cooling schedule',['linear','exponential','boltzmann'],'exponential'), ps('output_var','Output','sa_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('solution')],
    toSq: p=>`let ${p.output_var} = simulated_annealing(${p.objective_fn}, T_start=${p.T_start})`,
  },
  {
    id:'pso_opt', label:'Particle Swarm', cat:'optimization',
    color:'#B45309', icon:'PSO',
    info:'Particle Swarm Optimisation: swarm intelligence for continuous parameter spaces.',
    params:[ps('objective_fn','Objective function','cost_fn'), pn('n_particles','Particles',30,5,1000), pn('max_iter','Iterations',200,10,10000), pn('omega','Inertia ω',0.7,0,2), pn('c1','Cognitive c₁',1.5,0,4), pn('c2','Social c₂',1.5,0,4), ps('output_var','Output','pso_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('solution')],
    toSq: p=>`let ${p.output_var} = pso(${p.objective_fn}, n=${p.n_particles})`,
  },
  {
    id:'lbfgs_opt', label:'L-BFGS-B', cat:'optimization',
    color:'#B45309', icon:'BFGS',
    info:'Limited-memory BFGS with box constraints. Best for smooth, differentiable landscapes.',
    params:[ps('objective_fn','Objective + gradient fn','cost_fn'), pj('initial_params','Initial params','[0.1, 0.2]'), pj('bounds','Bounds per param (null=unbounded)','null'), pn('max_iter','Max iterations',1000,1,100000), ps('output_var','Output','lbfgs_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('params'), cOut('value')],
    toSq: p=>`let ${p.output_var} = lbfgs(${p.objective_fn}, max_iter=${p.max_iter})`,
  },
  {
    id:'bayesian_opt', label:'Bayesian Optimisation', cat:'optimization',
    color:'#B45309', icon:'BO',
    info:'Sample-efficient optimisation using Gaussian Process surrogate model. Ideal for expensive objectives.',
    params:[ps('objective_fn','Objective function','cost_fn'), pj('bounds','Search bounds','{"x":[0,3.14],"y":[0,3.14]}'), pn('n_initial','Initial random samples',5,1,100), pn('n_iter','BO iterations',25,5,1000), psel('acquisition','Acquisition fn',['EI','UCB','PI'],'EI'), ps('output_var','Output','bo_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('params'), cOut('gp_model')],
    toSq: p=>`let ${p.output_var} = bayesian_opt(${p.objective_fn}, n_iter=${p.n_iter})`,
  },
  {
    id:'maxcut_block', label:'Max-Cut', cat:'optimization',
    color:'#B45309', icon:'CUT',
    info:'Max-Cut problem: partition graph vertices to maximise cut edges. QAOA benchmark problem.',
    params:[pj('edges','Edge list','[[0,1],[1,2],[2,3],[3,0]]'), psel('solver','Solver',['QAOA','GoemansWilliamson','BruteForce','SDP'],'QAOA'), pn('p_layers','QAOA layers p',2,1,20), ps('output_var','Output partition','maxcut_result'), ...BYPASS],
    inputs:[], outputs:[cOut('partition'), cOut('cut_value')],
    toSq: p=>`let ${p.output_var} = max_cut(${p.edges}, solver="${p.solver}")`,
  },
  {
    id:'tsp_block', label:'Travelling Salesman', cat:'optimization',
    color:'#B45309', icon:'TSP',
    info:'Travelling Salesman Problem on quantum hardware via QAOA or quantum annealing.',
    params:[pj('distance_matrix','Distance matrix','[[0,2,3],[2,0,1],[3,1,0]]'), psel('solver','Solver',['QAOA','D-Wave','Genetic','NN_heuristic'],'QAOA'), pn('p_layers','QAOA layers',3,1,20), ps('output_var','Optimal route','tsp_result'), ...BYPASS],
    inputs:[], outputs:[cOut('route'), cOut('distance')],
    toSq: p=>`let ${p.output_var} = tsp(distance_matrix, solver="${p.solver}")`,
  },
  {
    id:'portfolio_opt', label:'Portfolio Optimisation', cat:'optimization',
    color:'#B45309', icon:'PORT',
    info:'Mean-variance portfolio optimisation (Markowitz). Binary or continuous allocation.',
    params:[ps('returns_var','Expected returns','returns'), ps('cov_var','Covariance matrix','cov_matrix'), pn('risk_aversion','Risk aversion λ',1.0,0,100), psel('solver',  'Solver',['QAOA','classical_QP','SA'],'classical_QP'), pn('n_assets','Assets to select',5,1,50), ps('output_var','Portfolio weights','portfolio'), ...BYPASS],
    inputs:[aIn('returns'), aIn('cov')], outputs:[cOut('weights'), cOut('sharpe')],
    toSq: p=>`let ${p.output_var} = portfolio_opt(${p.returns_var}, lambda=${p.risk_aversion})`,
  },
  {
    id:'linear_prog', label:'Linear Programming', cat:'optimization',
    color:'#B45309', icon:'LP',
    info:'Minimise cᵀx subject to Ax≤b, x≥0. Uses scipy.optimize.linprog.',
    params:[ps('c_var','Objective coefficients c','c'), ps('A_var','Constraint matrix A','A'), ps('b_var','Constraint vector b','b'), psel('method','Method',['highs','simplex','revised_simplex','interior-point'],'highs'), ps('output_var','Solution','lp_result'), ...BYPASS],
    inputs:[aIn('c'), aIn('A'), aIn('b')], outputs:[cOut('x'), cOut('objective_value')],
    toSq: p=>`let ${p.output_var} = linprog(${p.c_var}, ${p.A_var}, ${p.b_var})`,
  },
  {
    id:'integer_prog', label:'Integer Programming', cat:'optimization',
    color:'#B45309', icon:'ILP',
    info:'Mixed-integer linear programming with branch-and-bound.',
    params:[ps('c_var','Objective','c'), ps('A_var','Constraints A','A'), ps('b_var','Bounds b','b'), pj('int_vars','Integer variable indices','[0,1,2]'), ps('output_var','Solution','ilp_result'), ...BYPASS],
    inputs:[aIn('problem')], outputs:[cOut('solution')],
    toSq: p=>`let ${p.output_var} = integer_prog(${p.c_var}, ${p.A_var}, ${p.b_var})`,
  },
  {
    id:'qubo_block', label:'QUBO Formulation', cat:'optimization',
    color:'#B45309', icon:'QUBO',
    info:'Quadratic Unconstrained Binary Optimisation: x᷊Qx form for quantum annealers and QAOA.',
    params:[ps('problem_var','Problem (dict or matrix)','problem'), psel('solver','Solver',['D-Wave','SA','QAOA','exact'],'SA'), ps('output_var','Output solution','qubo_result'), ...BYPASS],
    inputs:[aIn('Q')], outputs:[cOut('x'), cOut('energy')],
    toSq: p=>`let ${p.output_var} = qubo_solve(${p.problem_var})`,
  },
  {
    id:'cvx_opt', label:'Convex Optimisation', cat:'optimization',
    color:'#B45309', icon:'CVX',
    info:'Solve convex programs via CVXPY (LP, QP, SOCP, SDP).',
    params:[pc('problem_code','CVXPY problem','# x = cp.Variable(n)\n# objective = cp.Minimize(...)'), ps('output_var','Solution','cvx_result'), ...BYPASS],
    inputs:[], outputs:[cOut('solution'), cOut('objective')],
    toSq: p=>`let ${p.output_var} = cvx_solve(...)`,
  },
  {
    id:'grid_search', label:'Grid Search', cat:'optimization',
    color:'#B45309', icon:'GRID',
    info:'Exhaustive hyperparameter grid search with optional cross-validation.',
    params:[ps('estimator_var','Estimator','model'), pj('param_grid','Parameter grid','{"C":[0.1,1,10],"gamma":[0.01,0.1]}'), pn('cv_folds','CV folds',5,2,20), psel('scoring','Scoring',['accuracy','f1','roc_auc','r2','neg_mse'],'accuracy'), ps('output_var','Best params','best_params'), ...BYPASS],
    inputs:[aIn('model'), aIn('X'), aIn('y')], outputs:[cOut('best_params'), cOut('cv_results')],
    toSq: p=>`let ${p.output_var} = grid_search(${p.estimator_var}, ${p.param_grid})`,
  },
  {
    id:'nelder_mead', label:'Nelder-Mead', cat:'optimization',
    color:'#B45309', icon:'NM',
    info:'Simplex method: robust derivative-free optimisation. Reliable for low-dimensional smooth landscapes.',
    params:[ps('objective_fn','Objective function','cost_fn'), pj('x0','Initial guess','[0.5, 0.5]'), pn('xatol','Absolute tolerance',1e-6,1e-12,0.1), pn('max_iter','Max iterations',500,10,100000), ps('output_var','Output','nm_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('params'), cOut('value')],
    toSq: p=>`let ${p.output_var} = nelder_mead(${p.objective_fn})`,
  },
  {
    id:'diff_evolution', label:'Differential Evolution', cat:'optimization',
    color:'#B45309', icon:'DE',
    info:'Population-based global optimiser. Excellent for multimodal continuous functions.',
    params:[ps('objective_fn','Objective function','cost_fn'), pj('bounds','Bounds','[[0,3.14],[0,3.14]]'), pn('popsize','Pop size multiplier',15,5,50), pn('mutation','Mutation factor',0.8,0.5,2), pn('recombination','Recombination',0.7,0,1), ps('output_var','Output','de_result'), ...BYPASS],
    inputs:[aIn('fn')], outputs:[cOut('solution')],
    toSq: p=>`let ${p.output_var} = differential_evolution(${p.objective_fn})`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // NLP (16 blocks)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'tokenizer_block', label:'Tokenizer', cat:'nlp',
    color:'#6D28D9', icon:'TOK',
    info:'Split text into tokens: BPE, WordPiece, SentencePiece, or whitespace.',
    params:[ps('text_var','Input text variable','text'), psel('tokenizer','Tokenizer',['BPE','WordPiece','SentencePiece','whitespace','char'],'WordPiece'), ps('model_name','Model/vocab','bert-base-uncased'), pn('max_length','Max length',512,1,8192), pb('padding','Pad to max_length',false), ps('output_var','Output tokens','tokens'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('tokens'), cOut('input_ids')],
    toSq: p=>`let ${p.output_var} = tokenize(${p.text_var}, model="${p.model_name}")`,
  },
  {
    id:'sentiment_block', label:'Sentiment Analysis', cat:'nlp',
    color:'#6D28D9', icon:'😊',
    info:'Classify text sentiment: positive/negative/neutral with confidence score.',
    params:[ps('text_var','Input text','text'), psel('model','Model',['DistilBERT','BERT','RoBERTa','VADER','TextBlob'],'DistilBERT'), psel('granularity','Granularity',['binary','3-class','5-class'],'3-class'), ps('output_var','Output sentiment','sentiment'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('sentiment'), cOut('score')],
    toSq: p=>`let ${p.output_var} = sentiment(${p.text_var}, model="${p.model}")`,
  },
  {
    id:'ner_block', label:'Named Entity Recognition', cat:'nlp',
    color:'#6D28D9', icon:'NER',
    info:'Extract entities: PERSON, ORG, GPE, DATE, MONEY, GENE, DRUG etc.',
    params:[ps('text_var','Input text','text'), psel('model','Model',['spaCy-en','BERT-NER','bioNER','sci-spaCy'],'spaCy-en'), pj('entity_types','Entity types','["PERSON","ORG","GPE","DATE"]'), ps('output_var','Output entities','entities'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('entities')],
    toSq: p=>`let ${p.output_var} = ner(${p.text_var}, model="${p.model}")`,
  },
  {
    id:'summarize_block', label:'Summarization', cat:'nlp',
    color:'#6D28D9', icon:'∑TXT',
    info:'Abstractive or extractive text summarisation.',
    params:[ps('text_var','Input text','text'), psel('method','Method',['abstractive','extractive','hybrid'],'abstractive'), psel('model','Model',['BART','T5','Pegasus','LED','LexRank'],'BART'), pn('max_length','Max summary tokens',150,10,2048), ps('output_var','Output summary','summary'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('summary')],
    toSq: p=>`let ${p.output_var} = summarize(${p.text_var}, max_length=${p.max_length})`,
  },
  {
    id:'translation_block', label:'Translation', cat:'nlp',
    color:'#6D28D9', icon:'🌐',
    info:'Neural machine translation: 200 language pairs via NLLB-200.',
    params:[ps('text_var','Input text','text'), ps('src_lang','Source language','en'), ps('tgt_lang','Target language','fr'), psel('model','Model',['NLLB-200','mBART','Helsinki-NLP','DeepL-API'],'NLLB-200'), ps('output_var','Translation','translated_text'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('translation')],
    toSq: p=>`let ${p.output_var} = translate(${p.text_var}, src="${p.src_lang}", tgt="${p.tgt_lang}")`,
  },
  {
    id:'qa_block', label:'Question Answering', cat:'nlp',
    color:'#6D28D9', icon:'Q→A',
    info:'Extractive QA from context document or open-domain retrieval.',
    params:[ps('question_var','Question','question'), ps('context_var','Context document','context'), psel('model','Model',['BERT-SQuAD','RoBERTa-SQuAD','DPR+FiD','GPT-4'],'RoBERTa-SQuAD'), ps('output_var','Answer','answer'), ...BYPASS],
    inputs:[cIn('q'), cIn('ctx')], outputs:[cOut('answer'), cOut('score')],
    toSq: p=>`let ${p.output_var} = qa(${p.question_var}, ${p.context_var})`,
  },
  {
    id:'text_classify', label:'Text Classification', cat:'nlp',
    color:'#6D28D9', icon:'CLS',
    info:'Multi-class text classification: zero-shot or fine-tuned.',
    params:[ps('text_var','Input text','text'), pj('labels','Class labels','["science","sports","politics"]'), psel('model','Model',['zero-shot-BART','DistilBERT','SetFit','FastText'],'zero-shot-BART'), ps('output_var','Output label','label'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('label'), cOut('scores')],
    toSq: p=>`let ${p.output_var} = text_classify(${p.text_var}, labels=${p.labels})`,
  },
  {
    id:'topic_model', label:'Topic Modelling', cat:'nlp',
    color:'#6D28D9', icon:'TOP',
    info:'Discover latent topics: LDA, NMF, BERTopic.',
    params:[ps('corpus_var','Document corpus','docs'), psel('method','Method',['LDA','NMF','BERTopic','CTM'],'BERTopic'), pn('n_topics','Topics',10,2,500), ps('output_var','Topics','topics'), ...BYPASS],
    inputs:[cIn('docs')], outputs:[cOut('topics'), cOut('doc_topic_matrix')],
    toSq: p=>`let ${p.output_var} = topic_model(${p.corpus_var}, n=${p.n_topics})`,
  },
  {
    id:'keyword_extract', label:'Keyword Extraction', cat:'nlp',
    color:'#6D28D9', icon:'KEY',
    info:'Extract key phrases using RAKE, YAKE, KeyBERT, or TF-IDF.',
    params:[ps('text_var','Input text','text'), psel('method','Method',['KeyBERT','YAKE','RAKE','TF-IDF'],'KeyBERT'), pn('top_k','Top-K keywords',10,1,100), ps('output_var','Keywords','keywords'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('keywords')],
    toSq: p=>`let ${p.output_var} = keywords(${p.text_var}, k=${p.top_k})`,
  },
  {
    id:'coreference_block', label:'Coreference Resolution', cat:'nlp',
    color:'#6D28D9', icon:'CO-REF',
    info:'Resolve pronoun and noun phrase coreferences in text.',
    params:[ps('text_var','Input text','text'), psel('model','Model',['neuralcoref','allennlp','fastcoref'],'fastcoref'), ps('output_var','Resolved text','coref_result'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('clusters'), cOut('resolved')],
    toSq: p=>`let ${p.output_var} = coreference(${p.text_var})`,
  },
  {
    id:'dep_parse', label:'Dependency Parsing', cat:'nlp',
    color:'#6D28D9', icon:'DEP',
    info:'Parse syntactic dependencies: subject, object, modifier relationships.',
    params:[ps('text_var','Input text','text'), psel('model','Model',['spaCy','stanza','CoreNLP'],'spaCy'), ps('output_var','Dependency tree','dep_tree'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('tree')],
    toSq: p=>`let ${p.output_var} = dep_parse(${p.text_var})`,
  },
  {
    id:'text_similarity', label:'Text Similarity', cat:'nlp',
    color:'#6D28D9', icon:'SIM',
    info:'Semantic text similarity using sentence embeddings or BM25.',
    params:[ps('text_a_var','Text A','text_a'), ps('text_b_var','Text B','text_b'), psel('method','Method',['cosine_sentence_embed','BM25','edit_distance','BLEU'],'cosine_sentence_embed'), ps('output_var','Similarity score','sim_score'), ...BYPASS],
    inputs:[cIn('a'), cIn('b')], outputs:[cOut('score')],
    toSq: p=>`let ${p.output_var} = text_similarity(${p.text_a_var}, ${p.text_b_var})`,
  },
  {
    id:'ocr_block', label:'OCR', cat:'nlp',
    color:'#6D28D9', icon:'OCR',
    info:'Optical Character Recognition: Tesseract, EasyOCR, PaddleOCR.',
    params:[ps('image_var','Image variable','img'), psel('engine','Engine',['Tesseract','EasyOCR','PaddleOCR','TrOCR'],'EasyOCR'), ps('language','Language','en'), ps('output_var','Extracted text','ocr_text'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('text'), cOut('bboxes')],
    toSq: p=>`let ${p.output_var} = ocr(${p.image_var}, engine="${p.engine}")`,
  },
  {
    id:'speech_transcribe', label:'Speech Transcription', cat:'nlp',
    color:'#6D28D9', icon:'🎤',
    info:'ASR: Whisper large-v3, Wav2Vec2, or cloud APIs.',
    params:[ps('audio_var','Audio file/variable','audio'), psel('model','Model',['whisper-large-v3','whisper-base','wav2vec2','deepgram'],'whisper-large-v3'), ps('language','Language (blank=auto)',''), pb('word_timestamps','Word timestamps',false), ps('output_var','Transcript','transcript'), ...BYPASS],
    inputs:[aIn('audio')], outputs:[cOut('transcript'), cOut('segments')],
    toSq: p=>`let ${p.output_var} = transcribe(${p.audio_var}, model="${p.model}")`,
  },
  {
    id:'tts_block', label:'Text-to-Speech', cat:'nlp',
    color:'#6D28D9', icon:'🔊',
    info:'Neural TTS: ElevenLabs, OpenAI TTS, Coqui, or edge-tts.',
    params:[ps('text_var','Input text','text'), psel('engine','Engine',['elevenlabs','openai-tts','coqui','edge-tts','pyttsx3'],'edge-tts'), ps('voice','Voice/speaker ID','en-US-AriaNeural'), pn('speed','Speed',1.0,0.5,2), ps('output_file','Output audio file','speech.mp3'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('audio_file')],
    toSq: p=>`let ${p.output_file} = tts(${p.text_var}, voice="${p.voice}")`,
  },
  {
    id:'regex_ner', label:'Regex NER', cat:'nlp',
    color:'#6D28D9', icon:'RE-NER',
    info:'Rule-based entity extraction using regex patterns for structured data (dates, phone numbers, emails, IDs).',
    params:[ps('text_var','Input text','text'), pj('patterns','Entity patterns (regex)','{"date":"\\\\d{4}-\\\\d{2}-\\\\d{2}","email":"[\\\\w.-]+@[\\\\w.-]+"}'), ps('output_var','Entities dict','re_entities'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('entities')],
    toSq: p=>`let ${p.output_var} = regex_ner(${p.text_var})`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // COMPUTER VISION (15 blocks)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'img_load', label:'Image Loader', cat:'cv',
    color:'#0369A1', icon:'📷',
    info:'Load image from file, URL, or numpy array. Returns tensor.',
    params:[ps('source','Source (file/URL/var)','image.jpg'), psel('format','Format',['RGB','BGR','RGBA','grayscale','tensor'],'RGB'), pj('resize','Resize [W,H] or null','null'), ps('output_var','Output image','img'), ...BYPASS],
    inputs:[], outputs:[aOut('image')],
    toSq: p=>`let ${p.output_var} = img_load("${p.source}")`,
  },
  {
    id:'img_preprocess', label:'Image Preprocess', cat:'cv',
    color:'#0369A1', icon:'⚙📷',
    info:'Normalise, resize, crop, augment for deep learning pipelines.',
    params:[ps('img_var','Image variable','img'), pj('transforms','Transform pipeline','[{"op":"resize","size":[224,224]},{"op":"normalize","mean":[0.485,0.456,0.406],"std":[0.229,0.224,0.225]}]'), ps('output_var','Output tensor','img_tensor'), ...BYPASS],
    inputs:[aIn('image')], outputs:[aOut('tensor')],
    toSq: p=>`let ${p.output_var} = img_preprocess(${p.img_var})`,
  },
  {
    id:'object_detect', label:'Object Detection', cat:'cv',
    color:'#0369A1', icon:'🔍📷',
    info:'Detect and localise objects: YOLO, DETR, Faster-RCNN, SAM.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['YOLOv9','YOLOv8','DETR','Faster-RCNN','RT-DETR'],'YOLOv8'), pn('conf_threshold','Confidence threshold',0.5,0,1), pj('classes','Filter classes (null=all)','null'), ps('output_var','Output detections','detections'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('detections'), cOut('annotated_img')],
    toSq: p=>`let ${p.output_var} = detect(${p.img_var}, model="${p.model}", conf=${p.conf_threshold})`,
  },
  {
    id:'img_classify_block', label:'Image Classification', cat:'cv',
    color:'#0369A1', icon:'CLS📷',
    info:'Classify image: ResNet, EfficientNet, ViT, CLIP zero-shot.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['ResNet-50','EfficientNet-B7','ViT-L/16','CLIP','DeiT'],'EfficientNet-B7'), pn('top_k','Top-K classes',5,1,1000), ps('output_var','Predictions','clf_result'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('labels'), cOut('scores')],
    toSq: p=>`let ${p.output_var} = img_classify(${p.img_var}, model="${p.model}")`,
  },
  {
    id:'img_segment_cv', label:'Image Segmentation', cat:'cv',
    color:'#0369A1', icon:'SEG📷',
    info:'Semantic or instance segmentation: SAM, Mask-RCNN, DeepLab.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['SAM','Mask-RCNN','DeepLabV3+','OneFormer'],'SAM'), psel('type','Type',['semantic','instance','panoptic'],'instance'), ps('output_var','Output masks','masks'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('masks'), cOut('labels')],
    toSq: p=>`let ${p.output_var} = img_segment(${p.img_var}, model="${p.model}")`,
  },
  {
    id:'face_detect', label:'Face Detection & Recognition', cat:'cv',
    color:'#0369A1', icon:'👤',
    info:'Detect, align, and recognise faces. DeepFace, InsightFace, MediaPipe.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['DeepFace','InsightFace','MediaPipe','MTCNN'],'InsightFace'), psel('task','Task',['detect','recognize','verify','align','emotion'],'detect'), ps('db_path','Face DB path (for recognition)','./faces/'), ps('output_var','Output','face_result'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('faces'), cOut('embeddings')],
    toSq: p=>`let ${p.output_var} = face_detect(${p.img_var}, model="${p.model}")`,
  },
  {
    id:'pose_estimate', label:'Pose Estimation', cat:'cv',
    color:'#0369A1', icon:'🏃',
    info:'Skeleton keypoint detection: MediaPipe, OpenPose, ViTPose.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['MediaPipe','OpenPose','ViTPose','MoveNet'],'MediaPipe'), psel('type','Type',['body','hand','face','whole'],'body'), ps('output_var','Keypoints','keypoints'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('keypoints'), cOut('annotated_img')],
    toSq: p=>`let ${p.output_var} = pose_estimate(${p.img_var})`,
  },
  {
    id:'depth_estimate', label:'Depth Estimation', cat:'cv',
    color:'#0369A1', icon:'3D📷',
    info:'Monocular depth estimation from single RGB image.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['DPT-Large','MiDaS','Depth-Anything','ZoeDepth'],'Depth-Anything'), ps('output_var','Depth map','depth_map'), ...BYPASS],
    inputs:[aIn('image')], outputs:[aOut('depth_map')],
    toSq: p=>`let ${p.output_var} = depth_estimate(${p.img_var})`,
  },
  {
    id:'optical_flow', label:'Optical Flow', cat:'cv',
    color:'#0369A1', icon:'→📷',
    info:'Estimate motion between consecutive frames: RAFT, FlowNet2.',
    params:[ps('frame1_var','Frame 1','frame1'), ps('frame2_var','Frame 2','frame2'), psel('model','Model',['RAFT','FlowNet2','TV-L1','Farneback'],'RAFT'), ps('output_var','Flow field','flow'), ...BYPASS],
    inputs:[aIn('f1'), aIn('f2')], outputs:[aOut('flow')],
    toSq: p=>`let ${p.output_var} = optical_flow(${p.frame1_var}, ${p.frame2_var})`,
  },
  {
    id:'img_generate', label:'Image Generation', cat:'cv',
    color:'#0369A1', icon:'✨📷',
    info:'Generative AI: Stable Diffusion, DALL-E, Midjourney-compatible APIs.',
    params:[ps('prompt','Text prompt',''), ps('negative_prompt','Negative prompt',''), psel('model','Model',['SD-XL','SD-3','DALL-E-3','Flux-1'],'SD-XL'), pn('width','Width',1024,64,2048), pn('height','Height',1024,64,2048), pn('steps','Inference steps',30,1,150), pn('guidance','Guidance scale',7.5,1,30), ps('output_var','Output image','gen_image'), ...BYPASS],
    inputs:[cIn('prompt')], outputs:[aOut('image')],
    toSq: p=>`let ${p.output_var} = img_generate("${p.prompt}", model="${p.model}")`,
  },
  {
    id:'video_process', label:'Video Processing', cat:'cv',
    color:'#0369A1', icon:'🎬',
    info:'Read, process, and write video frames. Apply CV pipeline per frame.',
    params:[ps('video_path','Video file path','video.mp4'), psel('operation','Operation',['extract_frames','apply_pipeline','detect_scenes','stabilize','super_resolve'],'extract_frames'), pn('fps','Output FPS (0=original)',0,0,240), ps('output_var','Output','video_result'), ...BYPASS],
    inputs:[], outputs:[aOut('frames'), cOut('metadata')],
    toSq: p=>`let ${p.output_var} = video_process("${p.video_path}", op="${p.operation}")`,
  },
  {
    id:'img_embed', label:'Image Embedding', cat:'cv',
    color:'#0369A1', icon:'[v]📷',
    info:'Extract visual embeddings for retrieval, similarity, and clustering.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['CLIP-ViT-L/14','DINOv2-ViT-L','ResNet-50','EfficientNet-B7'],'CLIP-ViT-L/14'), ps('output_var','Embedding','img_embedding'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('embedding')],
    toSq: p=>`let ${p.output_var} = img_embed(${p.img_var}, model="${p.model}")`,
  },
  {
    id:'anomaly_detect_img', label:'Anomaly Detection (Image)', cat:'cv',
    color:'#0369A1', icon:'⚠📷',
    info:'Unsupervised visual anomaly detection for industrial inspection.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['PatchCore','SPADE','PaDiM','FastFlow'],'PatchCore'), ps('output_var','Anomaly map','anomaly_map'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('anomaly_map'), cOut('score')],
    toSq: p=>`let ${p.output_var} = anomaly_detect(${p.img_var})`,
  },
  {
    id:'img_super_res', label:'Super Resolution', cat:'cv',
    color:'#0369A1', icon:'⬆📷',
    info:'Upscale image 2×/4×/8× using Real-ESRGAN, SRCNN, SwinIR.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['Real-ESRGAN','SwinIR','SRCNN','EDSR'],'Real-ESRGAN'), pn('scale','Scale factor',4,2,8), ps('output_var','Upscaled image','hires_img'), ...BYPASS],
    inputs:[aIn('image')], outputs:[aOut('image')],
    toSq: p=>`let ${p.output_var} = super_resolve(${p.img_var}, scale=${p.scale})`,
  },
  {
    id:'img_caption', label:'Image Captioning', cat:'cv',
    color:'#0369A1', icon:'💬📷',
    info:'Generate natural language description of an image.',
    params:[ps('img_var','Image variable','img'), psel('model','Model',['BLIP-2','LLaVA','CogVLM','GPT-4o-vision'],'BLIP-2'), ps('output_var','Caption','caption'), ...BYPASS],
    inputs:[aIn('image')], outputs:[cOut('caption')],
    toSq: p=>`let ${p.output_var} = img_caption(${p.img_var}, model="${p.model}")`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // QUANTUM FINANCE (14 blocks)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'option_pricing', label:'Quantum Option Pricing', cat:'finance',
    color:'#065F46', icon:'$Q',
    info:'Price European/Asian options via Quantum Amplitude Estimation. Quadratic speedup over Monte Carlo.',
    params:[ps('underlying','Underlying asset','S'), pn('S0','Spot price',100,0.01,1e9), pn('K','Strike price',100,0.01,1e9), pn('T','Maturity (years)',1,0.001,100), pn('r','Risk-free rate',0.05,0,1), pn('sigma','Volatility',0.2,0,5), psel('option_type','Type',['European_call','European_put','Asian','barrier'],'European_call'), psel('method','Method',['QAE','Monte_Carlo','Black-Scholes','Binomial'],'QAE'), ps('output_var','Option price','option_price'), ...BYPASS],
    inputs:[], outputs:[cOut('price'), cOut('greeks')],
    toSq: p=>`let ${p.output_var} = option_price(S0=${p.S0}, K=${p.K}, T=${p.T}, r=${p.r}, sigma=${p.sigma})`,
  },
  {
    id:'risk_analysis', label:'Risk Analysis', cat:'finance',
    color:'#065F46', icon:'VaR',
    info:'Value-at-Risk and Conditional VaR via Quantum Amplitude Estimation.',
    params:[ps('portfolio_var','Portfolio','portfolio'), pn('confidence','Confidence level',0.95,0.5,0.9999), psel('method','Method',['QAE','Monte_Carlo','historical','parametric'],'QAE'), pn('horizon_days','Horizon (days)',1,1,252), ps('output_var','Output risk','risk_metrics'), ...BYPASS],
    inputs:[aIn('portfolio')], outputs:[cOut('var'), cOut('cvar')],
    toSq: p=>`let ${p.output_var} = risk_analysis(${p.portfolio_var}, conf=${p.confidence})`,
  },
  {
    id:'markowitz_quantum', label:'Quantum Markowitz', cat:'finance',
    color:'#065F46', icon:'QMV',
    info:'Mean-variance portfolio optimisation using QAOA or quantum annealing on QUBO formulation.',
    params:[ps('returns_var','Returns series','returns'), ps('cov_var','Covariance matrix','cov'), pn('n_assets_select','Assets to select',5,1,50), pn('risk_aversion','Risk aversion',1.0,0,100), psel('solver','Solver',['QAOA','D-Wave','classical'],'QAOA'), ps('output_var','Weights','q_portfolio'), ...BYPASS],
    inputs:[aIn('returns'), aIn('cov')], outputs:[cOut('weights'), cOut('efficient_frontier')],
    toSq: p=>`let ${p.output_var} = quantum_markowitz(${p.returns_var}, ${p.cov_var})`,
  },
  {
    id:'fx_model', label:'FX Pricing', cat:'finance',
    color:'#065F46', icon:'FX',
    info:'Foreign exchange derivative pricing: Garman-Kohlhagen model.',
    params:[ps('spot_var','Spot rate','spot'), pn('K','Strike',1.0,0,1e6), pn('T','Maturity (years)',0.25,0.001,10), pn('r_d','Domestic rate',0.05,0,0.5), pn('r_f','Foreign rate',0.03,0,0.5), pn('sigma','Volatility',0.1,0,2), ps('output_var','Price','fx_price'), ...BYPASS],
    inputs:[], outputs:[cOut('price'), cOut('greeks')],
    toSq: p=>`let ${p.output_var} = fx_price(spot, K=${p.K}, T=${p.T}, r_d=${p.r_d}, r_f=${p.r_f})`,
  },
  {
    id:'yield_curve', label:'Yield Curve', cat:'finance',
    color:'#065F46', icon:'YC',
    info:'Bootstrap and interpolate yield curve from market instruments.',
    params:[ps('instruments_var','Market instruments','market_data'), psel('interpolation','Interpolation',['linear','cubic_spline','nelson_siegel','monotone_convex'],'cubic_spline'), ps('output_var','Yield curve','yield_curve'), ...BYPASS],
    inputs:[aIn('data')], outputs:[cOut('curve')],
    toSq: p=>`let ${p.output_var} = yield_curve(${p.instruments_var})`,
  },
  {
    id:'credit_risk', label:'Credit Risk', cat:'finance',
    color:'#065F46', icon:'CR',
    info:'Merton model, KMV, or CDS spread-based credit risk estimation.',
    params:[ps('firm_var','Firm data','firm'), psel('model','Model',['Merton','KMV','reduced_form','CDS_bootstrap'],'Merton'), ps('output_var','PD and LGD','credit_metrics'), ...BYPASS],
    inputs:[aIn('firm')], outputs:[cOut('pd'), cOut('lgd'), cOut('spread')],
    toSq: p=>`let ${p.output_var} = credit_risk(${p.firm_var}, model="${p.model}")`,
  },
  {
    id:'heston_model', label:'Heston Stochastic Vol', cat:'finance',
    color:'#065F46', icon:'HST',
    info:'Heston stochastic volatility model option pricing via characteristic function.',
    params:[pn('S0','Spot price',100,0,1e9), pn('v0','Initial variance',0.04,0,1), pn('kappa','Mean reversion κ',2.0,0,50), pn('theta','Long-run variance θ',0.04,0,1), pn('xi','Vol of vol ξ',0.3,0,5), pn('rho','Correlation ρ',-0.7,-1,1), pn('K','Strike',100,0,1e9), pn('T','Maturity',1,0,100), ps('output_var','Heston price','heston_price'), ...BYPASS],
    inputs:[], outputs:[cOut('price')],
    toSq: p=>`let ${p.output_var} = heston(S0=${p.S0}, v0=${p.v0}, kappa=${p.kappa})`,
  },
  {
    id:'backtesting_block', label:'Backtesting Engine', cat:'finance',
    color:'#065F46', icon:'BT',
    info:'Backtest trading strategy on historical data. Compute Sharpe, max drawdown, win rate.',
    params:[ps('strategy_fn','Strategy function','strategy_fn'), ps('data_var','OHLCV data','price_data'), pn('initial_capital','Initial capital',100000,100,1e12), ps('output_var','Backtest results','bt_result'), ...BYPASS],
    inputs:[aIn('data'), aIn('strategy')], outputs:[cOut('metrics'), cOut('equity_curve')],
    toSq: p=>`let ${p.output_var} = backtest(${p.strategy_fn}, ${p.data_var})`,
  },
  {
    id:'factor_model', label:'Factor Model', cat:'finance',
    color:'#065F46', icon:'FM',
    info:'Fama-French 3/5-factor, CAPM, Barra risk factor decomposition.',
    params:[ps('returns_var','Asset returns','returns'), psel('model','Model',['CAPM','FF3','FF5','Barra','PCA'],'FF3'), ps('factor_data_var','Factor data','factors'), ps('output_var','Factor loadings','factor_result'), ...BYPASS],
    inputs:[aIn('returns')], outputs:[cOut('loadings'), cOut('alpha')],
    toSq: p=>`let ${p.output_var} = factor_model(${p.returns_var}, model="${p.model}")`,
  },
  {
    id:'order_book', label:'Order Book Simulation', cat:'finance',
    color:'#065F46', icon:'LOB',
    info:'Limit order book simulation with market microstructure.',
    params:[psel('model','Market model',['LOBSTER','Santa_Fe','stochastic_LOB'],'Santa_Fe'), pn('n_agents','Agents',100,10,10000), pn('ticks','Simulation ticks',10000,100,1e9), ps('output_var','LOB state','lob_result'), ...BYPASS],
    inputs:[], outputs:[cOut('lob'), cOut('price_series')],
    toSq: p=>`let ${p.output_var} = order_book_sim(n_agents=${p.n_agents})`,
  },
  {
    id:'crypto_block', label:'Crypto Analytics', cat:'finance',
    color:'#065F46', icon:'₿',
    info:'DeFi, on-chain analytics, AMM pricing, MEV detection.',
    params:[ps('chain','Blockchain','ethereum'), ps('protocol','Protocol','uniswap_v3'), psel('analysis','Analysis',['amm_price','liquidity','mev','gas_forecast','yield'],'amm_price'), ps('output_var','Output','crypto_result'), ...BYPASS],
    inputs:[], outputs:[cOut('result')],
    toSq: p=>`let ${p.output_var} = crypto_analytics("${p.chain}", "${p.protocol}")`,
  },
  {
    id:'pairs_trading', label:'Pairs Trading', cat:'finance',
    color:'#065F46', icon:'PT',
    info:'Statistical arbitrage: cointegration test, z-score signals, mean-reversion.',
    params:[ps('asset_a_var','Asset A prices','price_a'), ps('asset_b_var','Asset B prices','price_b'), pn('z_entry','Z-score entry',2.0,0.5,5), pn('z_exit','Z-score exit',0.5,0,3), ps('output_var','Trading signals','pairs_signals'), ...BYPASS],
    inputs:[cIn('a'), cIn('b')], outputs:[cOut('signals'), cOut('pnl')],
    toSq: p=>`let ${p.output_var} = pairs_trading(${p.asset_a_var}, ${p.asset_b_var})`,
  },
  {
    id:'sentiment_fin', label:'Financial Sentiment', cat:'finance',
    color:'#065F46', icon:'FS',
    info:'NLP for earnings call transcripts, news, SEC filings.',
    params:[ps('text_var','Financial text','text'), psel('model','Model',['FinBERT','ProsusAI-finbert','GPT-4-finance'],'FinBERT'), ps('output_var','Sentiment','fin_sentiment'), ...BYPASS],
    inputs:[cIn('text')], outputs:[cOut('sentiment'), cOut('entities')],
    toSq: p=>`let ${p.output_var} = fin_sentiment(${p.text_var})`,
  },
  {
    id:'quantum_ml_finance', label:'Quantum ML Finance', cat:'finance',
    color:'#065F46', icon:'QML$',
    info:'QML for fraud detection, credit scoring, and algorithmic trading.',
    params:[ps('X_train','Features','X_train'), ps('y_train','Labels','y_train'), psel('model','QML model',['QSVM','QNN','QKNN'],'QSVM'), ps('output_var','Model','qml_fin_model'), ...BYPASS],
    inputs:[aIn('X'), aIn('y')], outputs:[aOut('model')],
    toSq: p=>`let ${p.output_var} = quantum_finance_model(${p.X_train}, ${p.y_train})`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // CLIMATE & ENVIRONMENT (12 blocks)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'climate_model', label:'Climate Model', cat:'climate',
    color:'#166534', icon:'🌍',
    info:'General Circulation Model integration: temperature, precipitation, sea-level forecasting.',
    params:[ps('config_var','GCM config','gcm_config'), psel('model','GCM',['CESM2','CMIP6','ERA5-reanalysis','simple_EBM'],'simple_EBM'), pn('years','Simulation years',100,1,10000), ps('scenario','RCP/SSP scenario','SSP2-4.5'), ps('output_var','Climate output','climate_result'), ...BYPASS],
    inputs:[], outputs:[cOut('temperature'), cOut('precipitation')],
    toSq: p=>`let ${p.output_var} = climate_model(scenario="${p.scenario}", years=${p.years})`,
  },
  {
    id:'co2_model', label:'CO₂ Budget Model', cat:'climate',
    color:'#166534', icon:'CO₂',
    info:'Carbon cycle model: emissions, sinks, atmospheric concentration.',
    params:[pj('emissions_path','Emissions pathway','{"2024":37.5,"2030":30,"2050":0}'), psel('carbon_cycle','Carbon cycle',['MAGICC','simple_carbon','DICE'],'DICE'), ps('output_var','CO2 trajectory','co2_result'), ...BYPASS],
    inputs:[], outputs:[cOut('co2_ppm'), cOut('temperature_change')],
    toSq: p=>`let ${p.output_var} = co2_model(emissions=${p.emissions_path})`,
  },
  {
    id:'renewable_opt', label:'Renewable Energy Optimisation', cat:'climate',
    color:'#166534', icon:'☀⚡',
    info:'Optimal mix of solar, wind, storage for a grid region.',
    params:[ps('demand_var','Demand profile','demand'), ps('solar_resource_var','Solar resource','solar'), ps('wind_resource_var','Wind resource','wind'), pn('storage_hours','Storage hours',4,0,100), psel('solver','Solver',['QAOA','LP','MIP'],'LP'), ps('output_var','Optimal mix','energy_mix'), ...BYPASS],
    inputs:[aIn('demand')], outputs:[cOut('capacity_mix'), cOut('lcoe')],
    toSq: p=>`let ${p.output_var} = renewable_opt(${p.demand_var})`,
  },
  {
    id:'wildfire_predict', label:'Wildfire Prediction', cat:'climate',
    color:'#166534', icon:'🔥',
    info:'ML fire risk and spread prediction from satellite + weather data.',
    params:[ps('weather_var','Weather data','weather'), ps('vegetation_var','Vegetation map','vegetation'), psel('model','Model',['RandomForest','GBT','LSTM','DeepFire'],'GBT'), ps('output_var','Fire risk map','fire_risk'), ...BYPASS],
    inputs:[aIn('weather'), aIn('vegetation')], outputs:[cOut('risk_map')],
    toSq: p=>`let ${p.output_var} = wildfire_predict(${p.weather_var}, ${p.vegetation_var})`,
  },
  {
    id:'ocean_model', label:'Ocean Model', cat:'climate',
    color:'#166534', icon:'🌊',
    info:'Ocean circulation, sea surface temperature, acidification.',
    params:[ps('init_conditions','Initial conditions','ocean_init'), psel('model','Model',['MOM6','NEMO','simple_box'],'simple_box'), pn('years','Simulation years',50,1,1000), ps('output_var','Ocean state','ocean_result'), ...BYPASS],
    inputs:[], outputs:[cOut('sst'), cOut('circulation')],
    toSq: p=>`let ${p.output_var} = ocean_model(years=${p.years})`,
  },
  {
    id:'air_quality', label:'Air Quality Model', cat:'climate',
    color:'#166534', icon:'💨',
    info:'Atmospheric chemistry and PM2.5/ozone concentration forecasting.',
    params:[ps('emissions_var','Emissions inventory','emissions'), ps('met_var','Meteorology','met_data'), psel('model','Model',['CMAQ','WRF-Chem','simple_dispersion'],'simple_dispersion'), ps('output_var','Air quality','aq_result'), ...BYPASS],
    inputs:[aIn('emissions'), aIn('met')], outputs:[cOut('pm25'), cOut('ozone')],
    toSq: p=>`let ${p.output_var} = air_quality(${p.emissions_var})`,
  },
  {
    id:'hydrology_block', label:'Hydrology Model', cat:'climate',
    color:'#166534', icon:'🌧',
    info:'Rainfall-runoff, flood prediction, groundwater recharge.',
    params:[ps('precip_var','Precipitation','precip'), ps('dem_var','Digital elevation model','dem'), psel('model','Model',['VIC','SWAT','HBV','simple_HRU'],'HBV'), ps('output_var','Streamflow','streamflow'), ...BYPASS],
    inputs:[aIn('precipitation')], outputs:[cOut('streamflow'), cOut('flood_risk')],
    toSq: p=>`let ${p.output_var} = hydrology(${p.precip_var})`,
  },
  {
    id:'biodiversity_block', label:'Biodiversity Modelling', cat:'climate',
    color:'#166534', icon:'🦋',
    info:'Species distribution modelling under climate change scenarios.',
    params:[ps('occurrence_var','Species occurrences','occurrences'), ps('climate_var','Climate variables','climate_data'), psel('model','SDM',['MaxEnt','BioClim','RandomForest','Ensemble'],'MaxEnt'), ps('output_var','Habitat suitability','sdm_result'), ...BYPASS],
    inputs:[aIn('occurrences')], outputs:[cOut('habitat_map')],
    toSq: p=>`let ${p.output_var} = species_distribution(${p.occurrence_var})`,
  },
  {
    id:'solar_irradiance', label:'Solar Irradiance', cat:'climate',
    color:'#166534', icon:'☀',
    info:'Estimate GHI, DNI, DHI from location and time.',
    params:[pn('latitude','Latitude (°)',40.0,-90,90), pn('longitude','Longitude (°)',-74,180,180), ps('date_start','Start date','2024-01-01'), pn('n_days','Days',365,1,3650), ps('output_var','Irradiance','irradiance'), ...BYPASS],
    inputs:[], outputs:[cOut('ghi'), cOut('dni'), cOut('dhi')],
    toSq: p=>`let ${p.output_var} = solar_irradiance(lat=${p.latitude}, lon=${p.longitude})`,
  },
  {
    id:'carbon_offset', label:'Carbon Offset Calculator', cat:'climate',
    color:'#166534', icon:'🌱',
    info:'Calculate carbon offset for activities and projects.',
    params:[ps('activity_var','Activity data','activity'), psel('methodology','Methodology',['GHG_Protocol','ISO_14064','Gold_Standard'],'GHG_Protocol'), ps('output_var','CO₂ equivalent tons','carbon_offset'), ...BYPASS],
    inputs:[aIn('activity')], outputs:[cOut('co2_tons')],
    toSq: p=>`let ${p.output_var} = carbon_offset(${p.activity_var})`,
  },
  {
    id:'glacier_model', label:'Glacier Model', cat:'climate',
    color:'#166534', icon:'🧊',
    info:'Ice sheet and glacier mass balance under warming scenarios.',
    params:[ps('init_glacier','Glacier parameters','glacier_init'), psel('model','Model',['OGGM','simple_ELA','PISM'],'OGGM'), pn('temp_change_C','Temperature change (°C)',2.0,-5,10), pn('years','Simulation years',100,10,1000), ps('output_var','Mass balance','glacier_result'), ...BYPASS],
    inputs:[], outputs:[cOut('mass_balance'), cOut('sea_level_contribution')],
    toSq: p=>`let ${p.output_var} = glacier_model(delta_T=${p.temp_change_C}, years=${p.years})`,
  },
  {
    id:'life_cycle_assess', label:'Life Cycle Assessment', cat:'climate',
    color:'#166534', icon:'LCA',
    info:'ISO 14040/44 LCA for products, processes, and systems.',
    params:[ps('product_var','Product system','product'), ps('functional_unit','Functional unit','1 kg'), psel('method','Impact method',['ReCiPe','CML','TRACI','EF3.0'],'ReCiPe'), ps('output_var','LCA results','lca_result'), ...BYPASS],
    inputs:[aIn('product')], outputs:[cOut('impact_categories')],
    toSq: p=>`let ${p.output_var} = lca(${p.product_var}, method="${p.method}")`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // ROBOTICS & CONTROL (12 blocks)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'pid_controller', label:'PID Controller', cat:'robotics',
    color:'#7C2D12', icon:'PID',
    info:'Proportional-Integral-Derivative controller for process control.',
    params:[pn('Kp','Proportional gain Kp',1.0,0,1000), pn('Ki','Integral gain Ki',0.1,0,1000), pn('Kd','Derivative gain Kd',0.01,0,1000), pn('setpoint','Setpoint',0), pn('dt','Timestep (s)',0.01,1e-6,10), ps('output_var','Control signal','u'), ...BYPASS],
    inputs:[cIn('error','Error signal')], outputs:[cOut('u','Control signal')],
    toSq: p=>`let ${p.output_var} = pid(Kp=${p.Kp}, Ki=${p.Ki}, Kd=${p.Kd}, setpoint=${p.setpoint})`,
  },
  {
    id:'kalman_filter', label:'Kalman Filter', cat:'robotics',
    color:'#7C2D12', icon:'KF',
    info:'Optimal state estimation for linear systems with Gaussian noise.',
    params:[pj('F','State transition matrix F','[[1,0],[0,1]]'), pj('H','Observation matrix H','[[1,0]]'), pj('Q','Process noise Q','[[0.01,0],[0,0.01]]'), pj('R','Measurement noise R','[[0.1]]'), pj('P0','Initial covariance P₀','[[1,0],[0,1]]'), ps('output_var','State estimate','state_est'), ...BYPASS],
    inputs:[cIn('z','Measurement')], outputs:[cOut('state'), cOut('covariance')],
    toSq: p=>`let ${p.output_var} = kalman_filter(z, F, H, Q, R)`,
  },
  {
    id:'ekf_block', label:'Extended Kalman Filter', cat:'robotics',
    color:'#7C2D12', icon:'EKF',
    info:'Non-linear state estimation via Jacobian linearisation.',
    params:[ps('f_fn','State transition fn','f'), ps('h_fn','Observation fn','h'), ps('jac_f_fn','Jacobian of f','jac_f'), ps('jac_h_fn','Jacobian of h','jac_h'), ps('output_var','State estimate','ekf_state'), ...BYPASS],
    inputs:[cIn('z')], outputs:[cOut('state')],
    toSq: p=>`let ${p.output_var} = ekf(z, ${p.f_fn}, ${p.h_fn})`,
  },
  {
    id:'path_planning', label:'Path Planning', cat:'robotics',
    color:'#7C2D12', icon:'🗺',
    info:'A*, RRT*, D*, or DWA path planning in 2D/3D environments.',
    params:[pj('start','Start [x,y]','[0,0]'), pj('goal','Goal [x,y]','[10,10]'), ps('map_var','Occupancy grid','occ_map'), psel('algorithm','Algorithm',['A*','RRT*','D*','PRM','DWA'],'A*'), pb('smooth_path','Smooth path',true), ps('output_var','Path','path'), ...BYPASS],
    inputs:[aIn('map')], outputs:[cOut('path'), cOut('cost')],
    toSq: p=>`let ${p.output_var} = path_plan(start=${p.start}, goal=${p.goal}, algo="${p.algorithm}")`,
  },
  {
    id:'slam_block', label:'SLAM', cat:'robotics',
    color:'#7C2D12', icon:'SLAM',
    info:'Simultaneous Localisation And Mapping: ORB-SLAM3, GMapping, Cartographer.',
    params:[ps('sensor_var','Sensor data (LiDAR/camera)','sensor_data'), psel('algorithm','SLAM algorithm',['ORB-SLAM3','GMapping','Cartographer','LIO-SAM'],'ORB-SLAM3'), psel('sensor_type','Sensor type',['monocular','stereo','RGBD','LiDAR'],'RGBD'), ps('output_var','Map and pose','slam_result'), ...BYPASS],
    inputs:[aIn('sensor')], outputs:[aOut('map'), cOut('pose')],
    toSq: p=>`let ${p.output_var} = slam(${p.sensor_var}, algo="${p.algorithm}")`,
  },
  {
    id:'rl_agent', label:'RL Agent', cat:'robotics',
    color:'#7C2D12', icon:'RL',
    info:'Reinforcement learning: PPO, SAC, TD3, DQN for robot control.',
    params:[ps('env_name','Gym environment','CartPole-v1'), psel('algorithm','RL algorithm',['PPO','SAC','TD3','DQN','A3C'],'PPO'), pn('total_steps','Total training steps',1000000,1000,1e9), pn('n_envs','Parallel envs',4,1,64), ps('output_model','Trained model','rl_policy'), ...BYPASS],
    inputs:[], outputs:[aOut('policy'), cOut('rewards')],
    toSq: p=>`let ${p.output_model} = rl_train("${p.env_name}", algo="${p.algorithm}", steps=${p.total_steps})`,
  },
  {
    id:'robot_kinematics', label:'Robot Kinematics', cat:'robotics',
    color:'#7C2D12', icon:'🦾',
    info:'Forward and inverse kinematics for robotic arms (DH parameters).',
    params:[pj('dh_params','DH parameters','[{"a":0,"d":0.5,"alpha":1.5708,"theta":0}]'), psel('task','Task',['forward_kinematics','inverse_kinematics','jacobian'],'forward_kinematics'), pj('joint_angles','Joint angles (rad)','[0,0,0,0,0,0]'), ps('output_var','End-effector pose','ee_pose'), ...BYPASS],
    inputs:[cIn('angles')], outputs:[cOut('pose'), cOut('jacobian')],
    toSq: p=>`let ${p.output_var} = kinematics(joints=${p.joint_angles}, task="${p.task}")`,
  },
  {
    id:'motion_control', label:'Motion Control', cat:'robotics',
    color:'#7C2D12', icon:'⚙🤖',
    info:'Trajectory tracking, impedance control, force-torque control.',
    params:[ps('trajectory_var','Desired trajectory','traj'), ps('state_var','Current state','robot_state'), psel('controller','Controller type',['PD','impedance','adaptive','computed_torque'],'impedance'), pn('stiffness','Stiffness K',100,0,10000), pn('damping','Damping D',10,0,1000), ps('output_var','Torques/commands','torques'), ...BYPASS],
    inputs:[cIn('traj'), cIn('state')], outputs:[cOut('commands')],
    toSq: p=>`let ${p.output_var} = motion_control(${p.trajectory_var}, ${p.state_var})`,
  },
  {
    id:'sensor_fusion', label:'Sensor Fusion', cat:'robotics',
    color:'#7C2D12', icon:'⊕S',
    info:'Fuse IMU, GPS, camera, LiDAR, encoder data.',
    params:[pj('sensors','Sensor list','["imu","gps","encoder"]'), psel('method','Fusion method',['EKF','UKF','particle_filter','complementary'],'EKF'), ps('output_var','Fused state','fused_state'), ...BYPASS],
    inputs:[aIn('imu'), aIn('gps'), aIn('lidar')], outputs:[cOut('state')],
    toSq: p=>`let ${p.output_var} = sensor_fusion(method="${p.method}")`,
  },
  {
    id:'grasp_plan', label:'Grasp Planning', cat:'robotics',
    color:'#7C2D12', icon:'✋',
    info:'Compute stable grasp poses for robotic manipulation.',
    params:[ps('object_var','Object pointcloud/mesh','object_pc'), psel('algorithm','Algorithm',['GraspNet','GPD','6-DOF-GraspNet','Dex-Net'],'GraspNet'), pn('n_candidates','Candidates',10,1,100), ps('output_var','Grasp candidates','grasps'), ...BYPASS],
    inputs:[aIn('object')], outputs:[cOut('grasps'), cOut('scores')],
    toSq: p=>`let ${p.output_var} = grasp_plan(${p.object_var})`,
  },
  {
    id:'sim_physics', label:'Physics Simulator', cat:'robotics',
    color:'#7C2D12', icon:'⚡🤖',
    info:'Real-time physics simulation: MuJoCo, Bullet, Isaac Gym.',
    params:[ps('scene_var','Scene description','scene'), psel('engine','Physics engine',['MuJoCo','PyBullet','Isaac','DART','CoppeliaSim'],'MuJoCo'), pn('sim_hz','Simulation Hz',1000,10,100000), pn('duration_s','Duration (s)',10,0.1,3600), ps('output_var','Simulation result','sim_result'), ...BYPASS],
    inputs:[aIn('scene')], outputs:[cOut('trajectories'), cOut('contacts')],
    toSq: p=>`let ${p.output_var} = physics_sim(${p.scene_var}, engine="${p.engine}")`,
  },
  {
    id:'nav_stack', label:'Navigation Stack', cat:'robotics',
    color:'#7C2D12', icon:'🧭',
    info:'Full navigation stack: global + local planner, costmap, recovery behaviours.',
    params:[pj('goal_pose','Goal pose','{"x":5,"y":3,"theta":0}'), ps('map_var','2D map','map'), psel('global_planner','Global planner',['A*','Dijkstra','NavFn','Smac'],'Smac'), psel('local_planner','Local planner',['DWA','TEB','MPPI','regulated_PP'],'TEB'), ps('output_var','Navigation result','nav_result'), ...BYPASS],
    inputs:[aIn('map'), cIn('goal')], outputs:[cOut('cmd_vel'), cOut('status')],
    toSq: p=>`let ${p.output_var} = navigate_to(${p.goal_pose})`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // EXPANDED: QUANTUM GATES (+20)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'givens_gate', label:'Givens Rotation', cat:'quantum_gate',
    color:'#6C3FC5', icon:'GR',
    info:'2-qubit Givens rotation for Gaussian boson sampling and quantum chemistry ansätze.',
    params:[psel('gate_type','Gate type',['2-qubit_Givens','Orbital_Rotation'],'2-qubit_Givens'), pq('qa','Qubit A',0), pq('qb','Qubit B',1), pa('theta','θ',Math.PI/4), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[qOut('ao'), qOut('bo')],
    toSq: p=>`# givens_rotation(q[${p.qa}], q[${p.qb}], ${p.theta.toFixed(4)})`,
  },
  {
    id:'pauli_x_half', label:'√X†  (SX†)', cat:'quantum_gate',
    color:'#6C3FC5', icon:'SX†',
    info:'Inverse √X gate. Native IBM gate. SX†² = X†.',
    params:[pq('target','Target',0), ...BYPASS],
    inputs:[qIn()], outputs:[qOut()],
    toSq: p=>`# sxdg(q[${p.target}])`,
  },
  {
    id:'rzx_gate', label:'RZX(θ)', cat:'quantum_gate',
    color:'#6C3FC5', icon:'RZX',
    info:'ZX rotation: exp(-iθ/2 Z⊗X). IBM native 2-qubit gate for cross-resonance.',
    params:[pq('qa','Qubit A',0), pq('qb','Qubit B',1), pa('theta','θ',Math.PI/4), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[qOut('ao'), qOut('bo')],
    toSq: p=>`# rzx(q[${p.qa}], q[${p.qb}], ${p.theta.toFixed(4)})`,
  },
  {
    id:'rxx_gate', label:'RXX(θ)', cat:'quantum_gate',
    color:'#6C3FC5', icon:'RXX',
    info:'XX Ising coupling: exp(-iθ/2 X⊗X). Used in trapped-ion Mølmer-Sørensen gates.',
    params:[pq('qa','Qubit A',0), pq('qb','Qubit B',1), pa('theta','θ',Math.PI/2), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[qOut('ao'), qOut('bo')],
    toSq: p=>`RZZ(q[${p.qa}], q[${p.qb}], ${p.theta.toFixed(4)})  # RXX via rotation`,
  },
  {
    id:'ryy_gate', label:'RYY(θ)', cat:'quantum_gate',
    color:'#6C3FC5', icon:'RYY',
    info:'YY Ising coupling: exp(-iθ/2 Y⊗Y).',
    params:[pq('qa','Qubit A',0), pq('qb','Qubit B',1), pa('theta','θ',Math.PI/2), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[qOut('ao'), qOut('bo')],
    toSq: p=>`# ryy(q[${p.qa}], q[${p.qb}], ${p.theta.toFixed(4)})`,
  },
  {
    id:'sqiswap_gate', label:'√iSWAP', cat:'quantum_gate',
    color:'#6C3FC5', icon:'√i↔',
    info:'Square root of iSWAP: Google Sycamore native gate.',
    params:[pq('qa','Qubit A',0), pq('qb','Qubit B',1), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[qOut('ao'), qOut('bo')],
    toSq: p=>`# sqrt_iswap(q[${p.qa}], q[${p.qb}])`,
  },
  {
    id:'dcx_gate', label:'DCX', cat:'quantum_gate',
    color:'#6C3FC5', icon:'DCX',
    info:'Double-CX (controlled-X in both directions sequentially). IBM hardware basis gate.',
    params:[pq('qa','Qubit A',0), pq('qb','Qubit B',1), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[qOut('ao'), qOut('bo')],
    toSq: p=>`CNOT(q[${p.qa}], q[${p.qb}])\nCNOT(q[${p.qb}], q[${p.qa}])  # DCX`,
  },
  {
    id:'xx_minus_yy', label:'XXminusYY', cat:'quantum_gate',
    color:'#6C3FC5', icon:'XX-YY',
    info:'(XX-YY)/2 rotation: IBM native gate for fermionic simulation.',
    params:[pq('qa','Qubit A',0), pq('qb','Qubit B',1), pa('theta','θ',0), pa('beta','β',0), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[qOut('ao'), qOut('bo')],
    toSq: p=>`# xx_minus_yy(q[${p.qa}], q[${p.qb}], ${p.theta.toFixed(4)}, ${p.beta.toFixed(4)})`,
  },
  {
    id:'xx_plus_yy', label:'XXplusYY', cat:'quantum_gate',
    color:'#6C3FC5', icon:'XX+YY',
    info:'(XX+YY)/2 rotation: IBM native gate.',
    params:[pq('qa','Qubit A',0), pq('qb','Qubit B',1), pa('theta','θ',0), pa('beta','β',0), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[qOut('ao'), qOut('bo')],
    toSq: p=>`# xx_plus_yy(q[${p.qa}], q[${p.qb}], ${p.theta.toFixed(4)}, ${p.beta.toFixed(4)})`,
  },
  {
    id:'csdg_gate', label:'CSdg', cat:'quantum_gate',
    color:'#6C3FC5', icon:'CSdg',
    info:'Controlled-S-dagger gate.',
    params:[pq('control','Control',0), pq('target','Target',1), ...BYPASS],
    inputs:[qIn('c'), qIn('t')], outputs:[qOut('co'), qOut('to')],
    toSq: p=>`# csdg(q[${p.control}], q[${p.target}])`,
  },
  {
    id:'ct_gate', label:'CT', cat:'quantum_gate',
    color:'#6C3FC5', icon:'CT',
    info:'Controlled-T gate.',
    params:[pq('control','Control',0), pq('target','Target',1), ...BYPASS],
    inputs:[qIn('c'), qIn('t')], outputs:[qOut('co'), qOut('to')],
    toSq: p=>`# ct(q[${p.control}], q[${p.target}])`,
  },
  {
    id:'c3x_gate', label:'C3X (3-control CX)', cat:'quantum_gate',
    color:'#6C3FC5', icon:'C3X',
    info:'Triple-controlled X gate. 4-qubit Toffoli generalisation.',
    params:[pq('c1','Control 1',0), pq('c2','Control 2',1), pq('c3','Control 3',2), pq('target','Target',3), ...BYPASS],
    inputs:[qIn('c1'), qIn('c2'), qIn('c3'), qIn('t')], outputs:[qOut('c1o'), qOut('c2o'), qOut('c3o'), qOut('to')],
    toSq: p=>`# c3x(q[${p.c1}], q[${p.c2}], q[${p.c3}], q[${p.target}])`,
  },
  {
    id:'c4x_gate', label:'C4X', cat:'quantum_gate',
    color:'#6C3FC5', icon:'C4X',
    info:'4-control CX gate.',
    params:[pq('c1','Control 1',0), pq('c2','Control 2',1), pq('c3','Control 3',2), pq('c4','Control 4',3), pq('target','Target',4), ...BYPASS],
    inputs:[qIn('c1'), qIn('c2'), qIn('c3'), qIn('c4'), qIn('t')], outputs:[qOut('to')],
    toSq: p=>`# c4x(q[${p.c1}],q[${p.c2}],q[${p.c3}],q[${p.c4}],q[${p.target}])`,
  },
  {
    id:'csx_gate', label:'CSX', cat:'quantum_gate',
    color:'#6C3FC5', icon:'CSX',
    info:'Controlled-SX gate. IBM native decomposition gate.',
    params:[pq('control','Control',0), pq('target','Target',1), ...BYPASS],
    inputs:[qIn('c'), qIn('t')], outputs:[qOut('co'), qOut('to')],
    toSq: p=>`# csx(q[${p.control}], q[${p.target}])`,
  },
  {
    id:'u1_gate', label:'U1(λ) — Phase', cat:'quantum_gate',
    color:'#6C3FC5', icon:'U1',
    info:'U1 gate: diagonal phase gate, equivalent to P gate. Qiskit legacy.',
    params:[pq('target','Target',0), pa('lambda','λ',Math.PI/4), ...BYPASS],
    inputs:[qIn()], outputs:[qOut()],
    toSq: p=>`P(q[${p.target}], ${p.lambda.toFixed(6)})  # U1 = P`,
  },
  {
    id:'u2_gate', label:'U2(φ,λ)', cat:'quantum_gate',
    color:'#6C3FC5', icon:'U2',
    info:'U2 gate: U3(π/2, φ, λ). Single Euler angle parametrisation.',
    params:[pq('target','Target',0), pa('phi','φ',0), pa('lambda','λ',Math.PI), ...BYPASS],
    inputs:[qIn()], outputs:[qOut()],
    toSq: p=>`U3(q[${p.target}], ${(Math.PI/2).toFixed(4)}, ${p.phi.toFixed(4)}, ${p.lambda.toFixed(4)})  # U2`,
  },
  {
    id:'global_phase', label:'Global Phase', cat:'quantum_gate',
    color:'#6C3FC5', icon:'e^iθ',
    info:'Apply global phase e^(iθ) to entire state. Unobservable but matters for controlled operations.',
    params:[pa('theta','Phase θ',Math.PI/4), ps('register','Register','q'), ...BYPASS],
    inputs:[rIn()], outputs:[rOut()],
    toSq: p=>`# global_phase(${p.register}, ${p.theta.toFixed(6)})`,
  },
  {
    id:'pauli_evo', label:'Pauli Evolution', cat:'quantum_gate',
    color:'#6C3FC5', icon:'e^iPt',
    info:'exp(-iθ P) for Pauli string P. Core VQE gate: time evolution under Hamiltonian term.',
    params:[ps('pauli_string','Pauli string','ZZ'), pa('theta','θ',Math.PI/4), ps('register','Register','q'), pj('qubits','Acting qubits','[0,1]'), ...BYPASS],
    inputs:[rIn()], outputs:[rOut()],
    toSq: p=>`RZZ(q[0], q[1], ${p.theta.toFixed(4)})  # Pauli evolution ${p.pauli_string}`,
  },
  {
    id:'trotter_step', label:'Trotter Step', cat:'quantum_gate',
    color:'#6C3FC5', icon:'TRO',
    info:'First or second-order Trotter-Suzuki step: e^(-iHt) ≈ ∏e^(-iHⱼt).',
    params:[ps('hamiltonian_var','Hamiltonian','H'), pn('time','Time t',0.1,0,100), psel('order','Trotter order',['1st','2nd','4th'],'2nd'), pn('n_steps','Trotter steps',1,1,1000), ps('register','Register','q'), ...BYPASS],
    inputs:[rIn(), aIn('H')], outputs:[rOut()],
    toSq: p=>`# trotter_step(${p.register}, H, t=${p.time}, order="${p.order}")`,
  },
  {
    id:'variational_form', label:'Variational Form', cat:'quantum_gate',
    color:'#6C3FC5', icon:'VAR',
    info:'Complete parameterised ansatz: EfficientSU2, RealAmplitudes, TwoLocal, UCCSD.',
    params:[ps('register','Register','q'), psel('ansatz','Ansatz',['EfficientSU2','RealAmplitudes','TwoLocal','UCCSD','CHC'],'EfficientSU2'), pn('reps','Repetitions',2,1,20), psel('entanglement','Entanglement',['linear','circular','full','sca'],'circular'), ps('param_prefix','Param prefix','θ'), pb('flatten_params','Flatten params',true), ...BYPASS],
    inputs:[rIn()], outputs:[rOut(), cOut('params_list','Parameter list')],
    toSq: p=>`# variational_ansatz(${p.register}, "${p.ansatz}", reps=${p.reps})`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // EXPANDED: QUANTUM ALGORITHMS (+18)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'vqd_block', label:'VQD', cat:'quantum_algo',
    color:'#2563EB', icon:'VQD',
    info:'Variational Quantum Deflation: compute excited state energies by orthogonality constraint.',
    params:[ps('hamiltonian','Hamiltonian','H'), pn('k_states','Number of states k',3,2,20), psel('ansatz','Ansatz',['UCCSD','EfficientSU2'],'EfficientSU2'), pn('shots','Shots',1000,100,100000), ps('output_var','Energies','excited_states'), ...BYPASS],
    inputs:[], outputs:[cOut('energies'), cOut('states')],
    toSq: p=>`let ${p.output_var} = vqd("${p.hamiltonian}", k=${p.k_states})`,
  },
  {
    id:'qite_block', label:'QITE', cat:'quantum_algo',
    color:'#2563EB', icon:'QITE',
    info:'Quantum Imaginary Time Evolution: e^(-βH)|ψ⟩ for state preparation.',
    params:[ps('hamiltonian','Hamiltonian','H'), ps('register','Register','q'), pn('beta','Imaginary time β',1.0,0.01,100), pn('db','Step size Δβ',0.05,0.001,1), ps('output_var','Ground state','qite_state'), ...BYPASS],
    inputs:[rIn()], outputs:[rOut(), cOut('energy')],
    toSq: p=>`let ${p.output_var} = qite(${p.register}, H, beta=${p.beta})`,
  },
  {
    id:'qdrift_block', label:'qDRIFT', cat:'quantum_algo',
    color:'#2563EB', icon:'qDRIFT',
    info:'Randomised first-order Hamiltonian simulation. Fewer gates than Trotterisation.',
    params:[ps('hamiltonian_var','Hamiltonian','H'), ps('register','Register','q'), pn('time','Simulation time t',1.0,0,1000), pn('n_samples','Samples N',100,10,10000), ps('output_var','Result','qdrift_result'), ...BYPASS],
    inputs:[rIn()], outputs:[rOut()],
    toSq: p=>`let ${p.output_var} = qdrift(${p.register}, H, t=${p.time}, N=${p.n_samples})`,
  },
  {
    id:'qsim_block', label:'Hamiltonian Simulation', cat:'quantum_algo',
    color:'#2563EB', icon:'H-SIM',
    info:'Simulate quantum system time evolution: Trotter, LCU, qubitisation, QSVT.',
    params:[ps('hamiltonian_var','Hamiltonian','H'), ps('register','Register','q'), pn('time','Simulation time t',1.0,0,1000), psel('method','Method',['Trotter-1','Trotter-2','LCU','qubitization','QSVT'],'Trotter-2'), pn('error','Target error ε',0.001,1e-10,1), ps('output_var','Final state','sim_state'), ...BYPASS],
    inputs:[rIn()], outputs:[rOut()],
    toSq: p=>`let ${p.output_var} = hamiltonian_sim(${p.register}, H, t=${p.time})`,
  },
  {
    id:'qsvt_block', label:'QSVT', cat:'quantum_algo',
    color:'#2563EB', icon:'QSVT',
    info:'Quantum Singular Value Transformation: unified framework for quantum algorithms.',
    params:[ps('block_encoding_var','Block encoding','block_enc'), ps('poly_coeff_var','Polynomial coefficients','poly'), ps('register','Register','q'), ps('output_var','Output','qsvt_result'), ...BYPASS],
    inputs:[rIn(), aIn('block_enc')], outputs:[rOut()],
    toSq: p=>`let ${p.output_var} = qsvt(${p.register}, ${p.block_encoding_var})`,
  },
  {
    id:'quantum_walk_search', label:'Quantum Walk Search', cat:'quantum_algo',
    color:'#2563EB', icon:'QWS',
    info:'Quantum walk-based search for marked vertices. √N speedup over classical random walk.',
    params:[psel('graph_type','Graph type',['hypercube','johnson','complete_bipartite'],'hypercube'), pn('n_vertices','Vertices',256,4,65536), pn('n_marked','Marked vertices',1,1,100), pn('shots','Shots',1000,100,100000), ps('output_var','Found vertex','qw_search'), ...BYPASS],
    inputs:[], outputs:[cOut('vertex'), cOut('prob_success')],
    toSq: p=>`let ${p.output_var} = qw_search("${p.graph_type}", n=${p.n_vertices})`,
  },
  {
    id:'quantum_counting', label:'Quantum Counting', cat:'quantum_algo',
    color:'#2563EB', icon:'QC',
    info:'Count marked elements in database. Uses QPE + Grover oracle.',
    params:[pn('n_qubits','Search space qubits',5,1,20), pn('n_precision','Precision qubits',5,3,20), ps('oracle_fn','Oracle function','oracle'), pn('shots','Shots',1000,100,10000), ps('output_var','Count','count_result'), ...BYPASS],
    inputs:[aIn('oracle')], outputs:[cOut('count'), cOut('frac_marked')],
    toSq: p=>`let ${p.output_var} = quantum_counting(n=${p.n_qubits})`,
  },
  {
    id:'quantum_arith', label:'Quantum Arithmetic', cat:'quantum_algo',
    color:'#2563EB', icon:'Q±×',
    info:'Quantum adder, multiplier, comparator for arithmetic circuits.',
    params:[pn('n_bits','Bit width',4,1,20), psel('operation','Operation',['add','subtract','multiply','compare','mod_exp'],'add'), ps('reg_a','Register A','a'), ps('reg_b','Register B','b'), ps('reg_out','Output register','c'), ...BYPASS],
    inputs:[rIn('a','Register A'), rIn('b','Register B')], outputs:[rOut('out','Result')],
    toSq: p=>`# quantum_${p.operation}(${p.reg_a}, ${p.reg_b}, ${p.reg_out})`,
  },
  {
    id:'quantum_ldpc', label:'Quantum LDPC', cat:'quantum_algo',
    color:'#2563EB', icon:'LDPC',
    info:'Quantum LDPC codes: good codes with constant rate and distance. Next-gen fault tolerance.',
    params:[pn('n_physical','Physical qubits',144,4,10000), pn('k_logical','Logical qubits',12,1,500), ps('output_var','Code','ldpc_code'), ...BYPASS],
    inputs:[], outputs:[rOut('code')],
    toSq: p=>`let ${p.output_var} = quantum_ldpc(n=${p.n_physical}, k=${p.k_logical})`,
  },
  {
    id:'qram_block', label:'QRAM', cat:'quantum_algo',
    color:'#2563EB', icon:'QRAM',
    info:'Quantum Random Access Memory: superposition memory access. Bucket-brigade or fanout architecture.',
    params:[ps('data_var','Classical data','data'), psel('architecture','Architecture',['bucket_brigade','fanout','hybrid'],'bucket_brigade'), pn('n_address','Address qubits',4,1,30), ps('output_var','Quantum data','qram'), ...BYPASS],
    inputs:[aIn('data')], outputs:[rOut('qdata')],
    toSq: p=>`let ${p.output_var} = qram(${p.data_var}, n_addr=${p.n_address})`,
  },
  {
    id:'variational_gibbs', label:'Quantum Gibbs State', cat:'quantum_algo',
    color:'#2563EB', icon:'GBB',
    info:'Prepare Gibbs thermal state ρ∝e^(-βH) using variational or QITE methods.',
    params:[ps('hamiltonian','Hamiltonian','H'), pn('beta','Inverse temperature β',1.0,0.001,100), psel('method','Method',['variational','QITE','METTS'],'variational'), ps('output_var','Gibbs state','gibbs_state'), ...BYPASS],
    inputs:[], outputs:[rOut('state')],
    toSq: p=>`let ${p.output_var} = gibbs_state(H, beta=${p.beta})`,
  },
  {
    id:'quantum_linear_sys', label:'Quantum Linear System', cat:'quantum_algo',
    color:'#2563EB', icon:'QLS',
    info:'VQLS: Variational Quantum Linear Solver for Ax=b without full HHL overhead.',
    params:[ps('A_var','Matrix A','A'), ps('b_var','Vector b','b'), psel('method','Method',['HHL','VQLS','CG_quantum'],'VQLS'), pn('shots','Shots',1000,100,100000), ps('output_var','Solution','x_qls'), ...BYPASS],
    inputs:[aIn('A'), aIn('b')], outputs:[rOut('x_state')],
    toSq: p=>`let ${p.output_var} = quantum_linear_solve(${p.A_var}, ${p.b_var})`,
  },
  {
    id:'qgan_block', label:'Quantum GAN', cat:'quantum_algo',
    color:'#2563EB', icon:'QGAN',
    info:'Quantum Generative Adversarial Network for quantum state generation.',
    params:[pn('n_qubits','Qubits',4,2,20), pn('n_layers','Generator layers',3,1,20), pn('epochs','Epochs',500,10,100000), ps('training_data_var','Training states','train_states'), ps('output_var','Generator','qgan_gen'), ...BYPASS],
    inputs:[aIn('data')], outputs:[aOut('generator')],
    toSq: p=>`let ${p.output_var} = qgan(n_qubits=${p.n_qubits}, epochs=${p.epochs})`,
  },
  {
    id:'shadow_tomo', label:'Classical Shadows', cat:'quantum_algo',
    color:'#2563EB', icon:'SHAD',
    info:'Efficient property estimation via classical shadows: O(log M) snapshots for M observables.',
    params:[ps('register','Register','q'), psel('shadow_type','Shadow type',['Pauli','Clifford','matchgate'],'Pauli'), pn('n_shadows','Snapshots K',100,10,100000), pj('observables','Observables','["Z0","Z1","Z0Z1"]'), ps('output_var','Estimates','shadow_result'), ...BYPASS],
    inputs:[rIn()], outputs:[cOut('estimates')],
    toSq: p=>`let ${p.output_var} = classical_shadows(${p.register}, K=${p.n_shadows})`,
  },
  {
    id:'quantum_bootstrap', label:'Quantum Bootstrap', cat:'quantum_algo',
    color:'#2563EB', icon:'QBS',
    info:'Statistical bootstrapping for quantum measurement uncertainties.',
    params:[ps('measurement_var','Measurement results','results'), pn('n_bootstrap','Bootstrap samples',1000,100,100000), pn('confidence','Confidence interval',0.95,0.5,0.9999), ps('output_var','CI bounds','bootstrap_ci'), ...BYPASS],
    inputs:[cIn('results')], outputs:[cOut('ci_lower'), cOut('ci_upper')],
    toSq: p=>`let ${p.output_var} = quantum_bootstrap(${p.measurement_var}, n=${p.n_bootstrap})`,
  },
  {
    id:'quant_kernel', label:'Quantum Kernel', cat:'quantum_algo',
    color:'#2563EB', icon:'QK',
    info:'Compute quantum kernel matrix K(xᵢ,xⱼ)=|⟨φ(xᵢ)|φ(xⱼ)⟩|² for ML.',
    params:[ps('X_var','Input data','X'), psel('feature_map','Feature map',['ZZFeatureMap','PauliFeatureMap','Custom'],'ZZFeatureMap'), pn('n_qubits','Qubits',4,1,20), pn('reps','Repetitions',2,1,10), ps('output_var','Kernel matrix','K'), ...BYPASS],
    inputs:[aIn('X')], outputs:[cOut('kernel_matrix')],
    toSq: p=>`let ${p.output_var} = quantum_kernel(${p.X_var}, map="${p.feature_map}")`,
  },
  {
    id:'mbl_sim', label:'Many-Body Localisation', cat:'quantum_algo',
    color:'#2563EB', icon:'MBL',
    info:'Simulate many-body localisation phase transition in disordered spin chains.',
    params:[pn('n_spins','Spins',10,4,30), pn('disorder_W','Disorder W',2.5,0,20), pn('J_coupling','Coupling J',1.0,0,10), pn('n_time_steps','Time steps',100,10,10000), ps('output_var','Entanglement entropy','mbl_result'), ...BYPASS],
    inputs:[], outputs:[cOut('entropy'), cOut('imbalance')],
    toSq: p=>`let ${p.output_var} = mbl_sim(n=${p.n_spins}, W=${p.disorder_W})`,
  },
  {
    id:'vqls_block', label:'VQLS', cat:'quantum_algo',
    color:'#2563EB', icon:'VQLS',
    info:'Variational Quantum Linear Solver: hybrid approach for linear systems without QRAM.',
    params:[ps('A_var','Matrix A (Pauli decomp)','A_pauli'), ps('b_state_var','b state circuit','b_circuit'), psel('ansatz','Ansatz',['EfficientSU2','TwoLocal'],'EfficientSU2'), pn('shots','Shots',1000,100,100000), ps('output_var','Solution state','vqls_result'), ...BYPASS],
    inputs:[aIn('A'), aIn('b')], outputs:[rOut('x_state')],
    toSq: p=>`let ${p.output_var} = vqls(${p.A_var}, ${p.b_state_var})`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // EXPANDED: QUANTUM MEASUREMENT (+8)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'weak_measure', label:'Weak Measurement', cat:'quantum_meas',
    color:'#4338CA', icon:'WM',
    info:'Partial collapse measurement: extracts partial information without full collapse.',
    params:[ps('register','Register','q'), pq('target','Target qubit',0), pn('strength','Measurement strength g',0.1,0,1), ps('output_var','Weak value','weak_val'), ...BYPASS],
    inputs:[rIn()], outputs:[rOut(), cOut('weak_value')],
    toSq: p=>`let ${p.output_var} = weak_measure(q[${p.target}], g=${p.strength})`,
  },
  {
    id:'povm_block', label:'POVM', cat:'quantum_meas',
    color:'#4338CA', icon:'POVM',
    info:'Positive Operator-Valued Measure: generalised quantum measurement.',
    params:[ps('register','Register','q'), pj('povm_elements','POVM elements','[]'), ps('output_var','Outcome','povm_result'), ...BYPASS],
    inputs:[rIn()], outputs:[cOut('outcome')],
    toSq: p=>`let ${p.output_var} = povm(${p.register})`,
  },
  {
    id:'mid_circuit_measure', label:'Mid-Circuit Measure', cat:'quantum_meas',
    color:'#4338CA', icon:'MCM',
    info:'Measure qubit mid-circuit and continue computation (dynamic circuits).',
    params:[pq('target','Target qubit',0), pb('reset_after','Reset after measure',false), ps('bit_var','Classical bit var','bit0'), ...BYPASS],
    inputs:[qIn()], outputs:[qOut(), cOut('bit')],
    toSq: p=>`let ${p.bit_var} = measure(q[${p.target}])`,
  },
  {
    id:'deferred_measure', label:'Deferred Measurement', cat:'quantum_meas',
    color:'#4338CA', icon:'DM',
    info:'Apply measurement deferral principle: move measurements to end of circuit.',
    params:[ps('register','Register','q'), pb('apply_principle','Apply principle',true), ...BYPASS],
    inputs:[rIn()], outputs:[rOut()],
    toSq: p=>`# deferred_measurement(${p.register})`,
  },
  {
    id:'parity_check', label:'Parity Check', cat:'quantum_meas',
    color:'#4338CA', icon:'PAR',
    info:'Measure multi-qubit parity P = Z⊗Z⊗...⊗Z without collapsing individual qubits.',
    params:[ps('register','Register','q'), pj('qubits','Qubits to measure','[0,1,2]'), psel('observable','Parity operator',['ZZZ','XXX','YYY','ZZI'],'ZZZ'), ps('output_var','Parity bit','parity'), ...BYPASS],
    inputs:[rIn()], outputs:[rOut(), cOut('parity')],
    toSq: p=>`let ${p.output_var} = parity_check(${p.register}, qubits=${p.qubits})`,
  },
  {
    id:'bell_measure', label:'Bell Measurement', cat:'quantum_meas',
    color:'#4338CA', icon:'B-M',
    info:'Project two qubits onto Bell basis. Used in teleportation and MBQC.',
    params:[pq('qa','Qubit A',0), pq('qb','Qubit B',1), ps('output_var','Bell outcome','bell_out'), ...BYPASS],
    inputs:[qIn('a'), qIn('b')], outputs:[cOut('outcome')],
    toSq: p=>`let ${p.output_var} = bell_measure(q[${p.qa}], q[${p.qb}])`,
  },
  {
    id:'density_matrix', label:'Density Matrix', cat:'quantum_meas',
    color:'#4338CA', icon:'ρ',
    info:'Compute full density matrix ρ = |ψ⟩⟨ψ|. Exponential cost — only feasible for ≤12 qubits.',
    params:[ps('register','Register','q'), pn('max_qubits','Max qubits (safety)',10,1,16), ps('output_var','Density matrix','rho'), ...BYPASS],
    inputs:[rIn()], outputs:[cOut('rho')],
    toSq: p=>`let ${p.output_var} = density_matrix(${p.register})`,
  },
  {
    id:'fidelity_block', label:'Fidelity', cat:'quantum_meas',
    color:'#4338CA', icon:'F',
    info:'Compute state fidelity F = |⟨ψ₁|ψ₂⟩|². Measures overlap between two quantum states.',
    params:[ps('reg_a','Register A','q1'), ps('reg_b','Register B','q2'), ps('output_var','Fidelity','fidelity'), ...BYPASS],
    inputs:[rIn('a','State A'), rIn('b','State B')], outputs:[cOut('fidelity')],
    toSq: p=>`let ${p.output_var} = fidelity(${p.reg_a}, ${p.reg_b})`,
  },

  // ───────────────────────────────────────────────────────────────────────
  // EXPANDED: NOISE MODELS (+6)
  // ───────────────────────────────────────────────────────────────────────
  {
    id:'coherent_error', label:'Coherent Error', cat:'noise',
    color:'#EA580C', icon:'~CE',
    info:'Systematic over/under-rotation error. Worst case for VQE accuracy — does NOT average out.',
    params:[pn('over_rotation','Over-rotation (rad)',0.01,-1,1), psel('apply_to','Apply to',['all_1q','Rx','Ry','H'],'all_1q'), ...BYPASS],
    inputs:[aIn()], outputs:[aOut('noisy')],
    toSq: p=>`noise_model = coherent_error(angle=${p.over_rotation})`,
  },
  {
    id:'leakage_noise', label:'Leakage to |2⟩', cat:'noise',
    color:'#EA580C', icon:'~L2',
    info:'Superconducting qubit leakage into non-computational |2⟩ state.',
    params:[pn('p_leak','Leakage probability',0.001,0,0.1), pn('p_seep','Seepage back to |1⟩',0.1,0,1), ...BYPASS],
    inputs:[aIn()], outputs:[aOut('noisy')],
    toSq: p=>`noise_model = leakage(p=${p.p_leak})`,
  },
  {
    id:'reset_error', label:'Reset Error', cat:'noise',
    color:'#EA580C', icon:'~RE',
    info:'Imperfect qubit reset: P(|1⟩ after reset) = p_reset_err.',
    params:[pn('p_reset_err','Reset error',0.01,0,1), ...BYPASS],
    inputs:[aIn()], outputs:[aOut('noisy')],
    toSq: p=>`noise_model = reset_error(p=${p.p_reset_err})`,
  },
  {
    id:'spam_noise', label:'SPAM Errors', cat:'noise',
    color:'#EA580C', icon:'~SPAM',
    info:'State Preparation And Measurement errors combined.',
    params:[pn('p_prep_err','Prep error',0.005,0,1), pn('p_meas_err','Measure error',0.01,0,1), ...BYPASS],
    inputs:[aIn()], outputs:[aOut('noisy')],
    toSq: p=>`noise_model = spam(prep=${p.p_prep_err}, meas=${p.p_meas_err})`,
  },
  {
    id:'two_qubit_noise', label:'2Q Gate Noise', cat:'noise',
    color:'#EA580C', icon:'~2Q',
    info:'Higher error rate for 2-qubit gates vs 1-qubit gates.',
    params:[pn('p_1q','1Q error rate',0.001,0,1), pn('p_2q','2Q error rate',0.01,0,1), ...BYPASS],
    inputs:[aIn()], outputs:[aOut('noisy')],
    toSq: p=>`noise_model = two_qubit_noise(p1q=${p.p_1q}, p2q=${p.p_2q})`,
  },
  {
    id:'device_noise', label:'Device Noise Model', cat:'noise',
    color:'#EA580C', icon:'~DEV',
    info:'Load real device calibration data to build accurate noise model.',
    params:[psel('device','Device',['ibm_brisbane','ibm_sherbrooke','google_sycamore','ionq_aria'],'ibm_brisbane'), pb('use_latest_calib','Use latest calibration',true), ps('output_noise_model','Noise model var','device_noise'), ...BYPASS],
    inputs:[], outputs:[aOut('noise_model')],
    toSq: p=>`let ${p.output_noise_model} = device_noise_model("${p.device}")`,
  },

];
